"""An operation may only declare a 422 if it can actually produce one.

FastAPI attaches `422 Validation Error` to any operation whose dependency tree
contains a validatable parameter. That is usually right, but a *shared*
dependency declaring one — an auth or tenant-binding dependency reading the
`Authorization` header via `Header(...)` — attaches it to every route in the
app, including routes that take no input at all. `GET /health` documented a 422
it could never return (#880 residual).

Hiding the parameter with `include_in_schema=False` is not enough: the
parameter still exists, so the 422 stays and only the parameter disappears from
the document. The fix is for those dependencies to read the header off
`Request`, which is what this asserts the outcome of.

The subject is the **committed artifact**, not the in-process
``faultmaven.main.app``. The app a test session happens to hold is not the app
that ships: several routers mount conditionally, so in the default test
environment it exposes 143 operations against the artifact's 146 — and the two
sets are neither subset nor superset. The OAuth, SSO and ``/metrics``
operations would never be checked (``/metrics`` is one of the routes this very
invariant fixes), while five ``/debug/*`` routes that are never published would
be. The in-process app is also collection-order dependent, because
``tests/integration/modules/auth/test_oauth_*.py`` set ``OAUTH_ENABLED`` and
drop ``faultmaven.main`` from ``sys.modules`` at import time.

Reading the artifact is not a weaker check: the ``api-contract-drift`` CI job
holds it byte-equal to the app built under the generator's pinned environment.
So this asserts the property over exactly the surface that ships, with no
subprocess and no ordering hazard.

The property is checked in both directions. A missing 422 on an operation that
*does* take input would be just as wrong — it would tell a client that malformed
input cannot be rejected.
"""

import json
from pathlib import Path

import pytest

SPEC_PATH = (
    Path(__file__).resolve().parents[3] / "docs" / "reference" / "api" / "openapi.json"
)


@pytest.fixture(scope="module")
def spec():
    """The published OpenAPI document, as committed."""
    assert SPEC_PATH.exists(), (
        f"{SPEC_PATH} is missing. It is generated by "
        "scripts/generate_api_docs.py and must be committed."
    )
    return json.loads(SPEC_PATH.read_text())


def _operations(spec):
    verbs = {"get", "post", "put", "patch", "delete", "head", "options", "trace"}
    return [
        (method.upper(), path, operation)
        for path, path_item in spec.get("paths", {}).items()
        for method, operation in path_item.items()
        if method in verbs and isinstance(operation, dict)
    ]


@pytest.mark.integration
def test_the_spec_covers_the_deployment_gated_routes(spec):
    """Guard the guard: the document must include the conditional routers.

    If the artifact were ever regenerated without them, every assertion below
    would still pass while silently covering less. These are the operations the
    in-process app omits, which is what made reading it the wrong subject.
    """
    paths = set(spec.get("paths", {}))
    missing = {
        p
        for p in (
            "/api/v1/auth/oauth/authorize",
            "/api/v1/auth/oauth/token",
            "/api/v1/auth/sso/login",
            "/metrics",
        )
        if p not in paths
    }
    assert not missing, (
        f"the committed spec is missing deployment-gated routes {sorted(missing)}; "
        "it should document the maximal deployed surface (see "
        "scripts/generate_api_docs.py PINNED_ENVIRONMENT)"
    )


@pytest.mark.integration
def test_422_is_declared_exactly_where_input_is_accepted(spec):
    """`422` appears iff the operation declares parameters or a request body."""
    spurious = []
    missing = []

    for method, path, operation in _operations(spec):
        accepts_input = bool(operation.get("parameters")) or bool(
            operation.get("requestBody")
        )
        declares_422 = "422" in operation.get("responses", {})

        if declares_422 and not accepts_input:
            spurious.append(f"{method} {path}")
        elif accepts_input and not declares_422:
            missing.append(f"{method} {path}")

    assert not spurious, (
        "These operations declare a 422 but accept no parameters and no request "
        "body, so they can never return one:\n"
        + "\n".join(f"  {op}" for op in sorted(spurious))
        + "\n\nThe usual cause is a shared dependency — auth or tenant binding — "
        "declaring a `Header(...)` parameter. Marking it `include_in_schema=False` "
        "hides the parameter but keeps the 422; the dependency needs to read the "
        "header off `Request` instead."
    )

    assert not missing, (
        "These operations accept input but do not declare a 422, so a client "
        "cannot tell that malformed input is rejected:\n"
        + "\n".join(f"  {op}" for op in sorted(missing))
    )
