"""001_clean_baseline

Revision ID: c4689af8aa3f
Revises: 
Create Date: 2026-05-07 01:21:21.786041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String, Text  # autogenerate emits bare type names inside dialect variants
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4689af8aa3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan_tier', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('max_members', sa.Integer(), server_default='5', nullable=False),
    sa.Column('max_cases', sa.Integer(), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('settings', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("plan_tier IN ('free', 'starter', 'pro', 'enterprise')", name='enterprises_plan_tier_check'),
    sa.CheckConstraint('LENGTH(TRIM(name)) > 0', name='enterprises_name_not_empty'),
    sa.PrimaryKeyConstraint('enterprise_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_enterprises_slug', 'enterprises', ['slug'], unique=True)
    op.create_table('oauth_revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index('idx_revoked_tokens_expires_at', 'oauth_revoked_tokens', ['expires_at'], unique=False)
    op.create_table('permissions',
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('resource', 'action', name='permissions_resource_action_unique')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=20), server_default='organization', nullable=False),
    sa.Column('is_system_role', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("scope IN ('system', 'enterprise', 'organization', 'team')", name='roles_scope_check'),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False),
    sa.Column('locale', sa.String(length=10), server_default='en-US', nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sso_provider', sa.String(length=50), nullable=True),
    sa.Column('sso_provider_id', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_password_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(hashed_password IS NOT NULL) OR (sso_provider IS NOT NULL)', name='users_password_or_sso'),
    sa.CheckConstraint('LENGTH(TRIM(display_name)) > 0', name='users_display_name_not_empty'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('sso_provider', 'sso_provider_id', name='users_sso_unique'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_enterprise_id'), 'users', ['enterprise_id'], unique=False)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_table('llm_config_overrides',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('oauth_authorization_codes',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('code_challenge', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('idx_auth_codes_expires_at', 'oauth_authorization_codes', ['expires_at'], unique=False)
    op.create_table('organizations',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('settings', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('LENGTH(TRIM(name)) > 0', name='organizations_name_not_empty'),
    sa.CheckConstraint('LENGTH(slug) > 0', name='organizations_slug_not_empty'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.enterprise_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('organization_id'),
    sa.UniqueConstraint('enterprise_id', 'slug', name='organizations_slug_unique_per_enterprise')
    )
    op.create_index(op.f('ix_organizations_enterprise_id'), 'organizations', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_organizations_owner_id'), 'organizations', ['owner_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invitation_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    op.create_index('ix_org_members_organization_id', 'organization_members', ['organization_id'], unique=False)
    op.create_index('ix_org_members_role_id', 'organization_members', ['role_id'], unique=False)
    op.create_table('teams',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('LENGTH(TRIM(name)) > 0', name='teams_name_not_empty'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('organization_id', 'name', name='teams_organization_name_unique')
    )
    op.create_index('ix_teams_organization_id', 'teams', ['organization_id'], unique=False)
    op.create_table('user_audit_log',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_user_audit_log_event_type'), 'user_audit_log', ['event_type'], unique=False)
    op.create_index('ix_user_audit_log_organization_id', 'user_audit_log', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_user_audit_log_user_id', 'user_audit_log', ['user_id', 'created_at'], unique=False)
    op.create_table('cases',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='inquiry', nullable=False),
    sa.Column('investigation_strategy', sa.Text(), nullable=True),
    sa.Column('current_turn', sa.Integer(), server_default='0', nullable=False),
    sa.Column('turns_without_progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('closure_reason', sa.String(length=100), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inquiry', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('problem_verification', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('working_conclusion', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('root_cause_conclusion', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('path_selection', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('escalation_state', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('documentation', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('progress', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('metadata', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status = 'inquiry' OR LENGTH(TRIM(description)) > 0", name='cases_description_required_post_inquiry'),
    sa.CheckConstraint("status IN ('inquiry', 'investigating', 'resolved', 'closed')", name='cases_status_check'),
    sa.CheckConstraint('LENGTH(TRIM(title)) > 0', name='cases_title_not_empty'),
    sa.CheckConstraint('current_turn >= 0', name='cases_current_turn_nonnegative'),
    sa.CheckConstraint('turns_without_progress >= 0', name='cases_turns_without_progress_nonnegative'),
    sa.CheckConstraint('version >= 1', name='cases_version_positive'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_closed_at'), 'cases', ['closed_at'], unique=False)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_last_activity_at'), 'cases', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_cases_organization_id'), 'cases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_team_id'), 'cases', ['team_id'], unique=False)
    op.create_index(op.f('ix_cases_user_id'), 'cases', ['user_id'], unique=False)
    op.create_table('knowledge_items',
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=20), server_default='organization', nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('source_suggestion_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.Text().with_variant(postgresql.ARRAY(String(length=50)), 'postgresql'), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), server_default='bge-m3', nullable=False),
    sa.Column('embedding_vector', sa.Text(), nullable=True),
    sa.Column('embedding_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=8), server_default='en', nullable=False),
    sa.Column('verification_level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('verification_reason', sa.String(length=512), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('helpful_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('not_helpful_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('metadata', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("item_type IN ('troubleshooting_guide', 'error_pattern', 'solution_template', 'api_documentation', 'configuration_guide', 'best_practice', 'faq', 'runbook')", name='knowledge_items_item_type_check'),
    sa.CheckConstraint("scope IN ('personal', 'team', 'organization', 'global')", name='knowledge_items_scope_check'),
    sa.CheckConstraint('embedding_version >= 1', name='knowledge_items_embedding_version_check'),
    sa.CheckConstraint('helpful_count >= 0', name='knowledge_items_helpful_count_check'),
    sa.CheckConstraint('not_helpful_count >= 0', name='knowledge_items_not_helpful_count_check'),
    sa.CheckConstraint('verification_level >= 0 AND verification_level <= 2', name='knowledge_items_verification_level_check'),
    sa.CheckConstraint('view_count >= 0', name='knowledge_items_view_count_check'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_knowledge_items_category'), 'knowledge_items', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_items_created_at'), 'knowledge_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_items_is_published'), 'knowledge_items', ['is_published'], unique=False)
    op.create_index(op.f('ix_knowledge_items_item_type'), 'knowledge_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_knowledge_items_last_retrieved_at'), 'knowledge_items', ['last_retrieved_at'], unique=False)
    op.create_index(op.f('ix_knowledge_items_organization_id'), 'knowledge_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_items_owner_id'), 'knowledge_items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_knowledge_items_scope'), 'knowledge_items', ['scope'], unique=False)
    op.create_index(op.f('ix_knowledge_items_source_suggestion_id'), 'knowledge_items', ['source_suggestion_id'], unique=False)
    op.create_index('ix_knowledge_items_tags', 'knowledge_items', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_knowledge_items_team_id'), 'knowledge_items', ['team_id'], unique=False)
    op.create_index(op.f('ix_knowledge_items_verification_level'), 'knowledge_items', ['verification_level'], unique=False)
    op.create_table('team_members',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('team_role', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_index('ix_team_members_team_id', 'team_members', ['team_id'], unique=False)
    op.create_table('case_actions',
    sa.Column('transition_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('transitioned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transition_id')
    )
    op.create_index(op.f('ix_case_actions_case_id'), 'case_actions', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_actions_organization_id'), 'case_actions', ['organization_id'], unique=False)
    op.create_table('case_checkpoints',
    sa.Column('checkpoint_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('case_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(snapshot_hash)) > 0', name='case_checkpoints_hash_not_empty'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_index(op.f('ix_case_checkpoints_case_id'), 'case_checkpoints', ['case_id'], unique=False)
    op.create_index('ix_case_checkpoints_case_turn', 'case_checkpoints', ['case_id', 'turn_number'], unique=False)
    op.create_index(op.f('ix_case_checkpoints_created_at'), 'case_checkpoints', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_checkpoints_organization_id'), 'case_checkpoints', ['organization_id'], unique=False)
    op.create_table('case_messages',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('turn_number', sa.Integer(), server_default='0', nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='case_messages_role_check'),
    sa.CheckConstraint('LENGTH(TRIM(content)) > 0', name='case_messages_content_not_empty'),
    sa.CheckConstraint('turn_number >= 0', name='case_messages_turn_nonnegative'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_case_messages_case_created', 'case_messages', ['case_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_case_messages_case_id'), 'case_messages', ['case_id'], unique=False)
    op.create_index('ix_case_messages_case_turn', 'case_messages', ['case_id', 'turn_number'], unique=False)
    op.create_index(op.f('ix_case_messages_created_at'), 'case_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_messages_organization_id'), 'case_messages', ['organization_id'], unique=False)
    op.create_table('case_tags',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("tag NOT LIKE '%,%'", name='case_tags_no_commas'),
    sa.CheckConstraint('LENGTH(TRIM(tag)) > 0', name='case_tags_tag_not_empty'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('case_id', 'tag', name='case_tags_unique')
    )
    op.create_index(op.f('ix_case_tags_case_id'), 'case_tags', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_tags_organization_id'), 'case_tags', ['organization_id'], unique=False)
    op.create_index(op.f('ix_case_tags_tag'), 'case_tags', ['tag'], unique=False)
    op.create_table('hypotheses',
    sa.Column('hypothesis_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='captured', nullable=False),
    sa.Column('likelihood', sa.Numeric(precision=3, scale=2), server_default='0.5', nullable=True),
    sa.Column('initial_likelihood', sa.Numeric(precision=3, scale=2), server_default='0.5', nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('generation_mode', sa.String(length=20), server_default='systematic', nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('retirement_reason', sa.Text(), nullable=True),
    sa.Column('refutation_reason', sa.String(length=200), nullable=True),
    sa.Column('generated_at_turn', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_updated_turn', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_progress_at_turn', sa.Integer(), server_default='0', nullable=False),
    sa.Column('iterations_without_progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('metadata', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('captured', 'active', 'validated', 'refuted', 'inconclusive', 'retired')", name='hypotheses_status_check'),
    sa.CheckConstraint('LENGTH(TRIM(statement)) > 0', name='hypotheses_statement_not_empty'),
    sa.CheckConstraint('likelihood IS NULL OR (likelihood >= 0 AND likelihood <= 1)', name='hypotheses_likelihood_range'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('hypothesis_id')
    )
    op.create_index(op.f('ix_hypotheses_case_id'), 'hypotheses', ['case_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_category'), 'hypotheses', ['category'], unique=False)
    op.create_index(op.f('ix_hypotheses_created_by'), 'hypotheses', ['created_by'], unique=False)
    op.create_index(op.f('ix_hypotheses_organization_id'), 'hypotheses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_status'), 'hypotheses', ['status'], unique=False)
    op.create_table('investigation_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('session_goal', sa.Text(), nullable=True),
    sa.Column('findings_summary', sa.Text(), nullable=True),
    sa.Column('total_token_usage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_agent_executions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('token_budget_limit', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'paused', 'completed', 'abandoned')", name='investigation_sessions_status_check'),
    sa.CheckConstraint('token_budget_limit IS NULL OR token_budget_limit >= 0', name='investigation_sessions_budget_check'),
    sa.CheckConstraint('total_agent_executions >= 0', name='investigation_sessions_executions_check'),
    sa.CheckConstraint('total_duration_ms IS NULL OR total_duration_ms >= 0', name='investigation_sessions_duration_check'),
    sa.CheckConstraint('total_token_usage >= 0', name='investigation_sessions_token_usage_check'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_investigation_sessions_case_id'), 'investigation_sessions', ['case_id'], unique=False)
    op.create_index(op.f('ix_investigation_sessions_created_at'), 'investigation_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_investigation_sessions_organization_id'), 'investigation_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_investigation_sessions_status'), 'investigation_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_investigation_sessions_user_id'), 'investigation_sessions', ['user_id'], unique=False)
    op.create_table('knowledge_suggestions',
    sa.Column('suggestion_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('knowledge_item_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending_review', nullable=False),
    sa.Column('suggested_title', sa.String(length=512), nullable=False),
    sa.Column('suggested_content', sa.Text(), nullable=False),
    sa.Column('suggested_type', sa.String(length=64), server_default='troubleshooting_guide', nullable=False),
    sa.Column('extracted_by', sa.String(length=36), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('include_messages', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('include_evidence', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('pii_scan_status', sa.String(length=32), server_default='not_scanned', nullable=False),
    sa.Column('pii_scan_result', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('pii_remediated_by', sa.String(length=36), nullable=True),
    sa.Column('pii_remediated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_case_title', sa.String(length=512), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('evidence_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("pii_scan_status IN ('not_scanned', 'scanning', 'clean', 'pii_detected', 'remediated', 'scan_failed')", name='knowledge_suggestions_pii_scan_status_check'),
    sa.CheckConstraint("status IN ('pending_review', 'approved', 'rejected', 'draft')", name='knowledge_suggestions_status_check'),
    sa.CheckConstraint('evidence_count >= 0', name='knowledge_suggestions_evidence_count_check'),
    sa.CheckConstraint('message_count >= 0', name='knowledge_suggestions_message_count_check'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extracted_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.item_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pii_remediated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('suggestion_id')
    )
    op.create_index(op.f('ix_knowledge_suggestions_case_id'), 'knowledge_suggestions', ['case_id'], unique=False)
    op.create_index(op.f('ix_knowledge_suggestions_created_at'), 'knowledge_suggestions', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_suggestions_extracted_by'), 'knowledge_suggestions', ['extracted_by'], unique=False)
    op.create_index(op.f('ix_knowledge_suggestions_knowledge_item_id'), 'knowledge_suggestions', ['knowledge_item_id'], unique=False)
    op.create_index(op.f('ix_knowledge_suggestions_organization_id'), 'knowledge_suggestions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_suggestions_pii_scan_status'), 'knowledge_suggestions', ['pii_scan_status'], unique=False)
    op.create_index(op.f('ix_knowledge_suggestions_status'), 'knowledge_suggestions', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('generated_by', sa.String(length=36), nullable=True),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('linked_to_closure', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=20), server_default='markdown', nullable=False),
    sa.Column('generation_status', sa.String(length=20), nullable=False),
    sa.Column('generation_time_ms', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("format IN ('markdown', 'html')", name='reports_format_check'),
    sa.CheckConstraint("generation_status IN ('generating', 'completed', 'failed')", name='reports_status_check'),
    sa.CheckConstraint("report_type IN ('resolution_summary', 'closure_summary')", name='reports_type_check'),
    sa.CheckConstraint('generation_time_ms >= 0 AND generation_time_ms <= 120000', name='reports_gen_time_check'),
    sa.CheckConstraint('version >= 1 AND version <= 5', name='reports_version_check'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('idx_reports_type_version', 'reports', ['case_id', 'report_type'], unique=False)
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=False)
    op.create_index(op.f('ix_reports_organization_id'), 'reports', ['organization_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('storage_ref', sa.String(length=1000), nullable=True),
    sa.Column('upload_source', sa.String(length=50), server_default='file_upload', nullable=False),
    sa.Column('uploaded_at_turn', sa.Integer(), server_default='0', nullable=False),
    sa.Column('preprocessing_summary', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(filename)) > 0', name='uploaded_files_filename_not_empty'),
    sa.CheckConstraint('size_bytes >= 0', name='uploaded_files_size_nonnegative'),
    sa.CheckConstraint('uploaded_at_turn >= 0', name='uploaded_files_turn_nonnegative'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_uploaded_files_case_id'), 'uploaded_files', ['case_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_content_hash'), 'uploaded_files', ['content_hash'], unique=False)
    op.create_index(op.f('ix_uploaded_files_organization_id'), 'uploaded_files', ['organization_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_uploaded_by'), 'uploaded_files', ['uploaded_by'], unique=False)
    op.create_table('agent_executions',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('agent_type', sa.String(length=64), nullable=False),
    sa.Column('agent_model', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='queued', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('token_usage', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('metadata', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("agent_type IN ('investigator', 'debugger', 'researcher', 'validator', 'reporter', 'custom')", name='agent_executions_agent_type_check'),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed', 'cancelled', 'timeout')", name='agent_executions_status_check'),
    sa.CheckConstraint('execution_duration_ms IS NULL OR execution_duration_ms >= 0', name='agent_executions_duration_check'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['investigation_sessions.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_agent_executions_agent_model'), 'agent_executions', ['agent_model'], unique=False)
    op.create_index(op.f('ix_agent_executions_agent_type'), 'agent_executions', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_executions_case_id'), 'agent_executions', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_created_at'), 'agent_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_executions_organization_id'), 'agent_executions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_session_id'), 'agent_executions', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_status'), 'agent_executions', ['status'], unique=False)
    op.create_table('conversion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('source_file_id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='processing', nullable=False),
    sa.Column('source_type', sa.String(length=20), server_default='document', nullable=False),
    sa.Column('failure_modes_detected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scope IN ('personal', 'team', 'organization', 'global')", name='conversion_jobs_scope_check'),
    sa.CheckConstraint("source_type IN ('document', 'case')", name='conversion_jobs_source_type_check'),
    sa.CheckConstraint("status IN ('processing', 'completed', 'failed', 'cancelled')", name='conversion_jobs_status_check'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['uploaded_files.file_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_jobs_case_id'), 'conversion_jobs', ['case_id'], unique=False)
    op.create_index(op.f('ix_conversion_jobs_organization_id'), 'conversion_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_conversion_jobs_source_file_id'), 'conversion_jobs', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_conversion_jobs_user_id'), 'conversion_jobs', ['user_id'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('form', sa.Enum('document', 'user_text', 'submitted_data', name='evidence_form', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('tags', sa.Text().with_variant(postgresql.ARRAY(String(length=50)), 'postgresql'), nullable=True),
    sa.Column('collected_at_turn', sa.Integer(), nullable=True),
    sa.Column('coverage_start_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coverage_end_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vectorized', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('metadata', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(content)) > 0', name='evidence_content_not_empty'),
    sa.CheckConstraint('reliability_score IS NULL OR (reliability_score >= 0 AND reliability_score <= 1)', name='evidence_reliability_range'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['uploaded_files.file_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index('ix_evidence_case_is_primary', 'evidence', ['case_id', 'is_primary'], unique=False)
    op.create_index(op.f('ix_evidence_category'), 'evidence', ['category'], unique=False)
    op.create_index(op.f('ix_evidence_collected_at_turn'), 'evidence', ['collected_at_turn'], unique=False)
    op.create_index('ix_evidence_coverage', 'evidence', ['case_id', 'coverage_start_ts', 'coverage_end_ts'], unique=False)
    op.create_index(op.f('ix_evidence_organization_id'), 'evidence', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_file_id'), 'evidence', ['source_file_id'], unique=False)
    op.create_index('ix_evidence_tags', 'evidence', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('solutions',
    sa.Column('solution_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('solution_type', sa.String(length=30), server_default='other', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='proposed', nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('estimated_effort', sa.String(length=50), nullable=True),
    sa.Column('immediate_action', sa.Text(), nullable=True),
    sa.Column('longterm_fix', sa.Text(), nullable=True),
    sa.Column('implementation_steps', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('commands', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('risks', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('verification_result', sa.Text(), nullable=True),
    sa.Column('verification_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('metadata', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='{}', nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('implemented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("risk_level IS NULL OR risk_level IN ('low', 'medium', 'high', 'critical')", name='solutions_risk_level_check'),
    sa.CheckConstraint("status IN ('proposed', 'accepted', 'rejected', 'implemented', 'verified')", name='solutions_status_check'),
    sa.CheckConstraint('LENGTH(TRIM(description)) > 0', name='solutions_description_not_empty'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.hypothesis_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('solution_id')
    )
    op.create_index(op.f('ix_solutions_case_id'), 'solutions', ['case_id'], unique=False)
    op.create_index(op.f('ix_solutions_created_by'), 'solutions', ['created_by'], unique=False)
    op.create_index(op.f('ix_solutions_hypothesis_id'), 'solutions', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_solutions_organization_id'), 'solutions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_solutions_status'), 'solutions', ['status'], unique=False)
    op.create_table('agent_tool_calls',
    sa.Column('tool_call_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('tool_input', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('tool_output', sa.Text().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'success', 'failed')", name='agent_tool_calls_status_check'),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name='agent_tool_calls_duration_check'),
    sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.execution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_call_id')
    )
    op.create_index(op.f('ix_agent_tool_calls_created_at'), 'agent_tool_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_execution_id'), 'agent_tool_calls', ['execution_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_organization_id'), 'agent_tool_calls', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_status'), 'agent_tool_calls', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_tool_name'), 'agent_tool_calls', ['tool_name'], unique=False)
    op.create_table('case_entities',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_value', sa.String(length=255), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('mention_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('in_error_context', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('first_seen_ts', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.evidence_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'entity_type', 'entity_value', 'evidence_id')
    )
    op.create_index('idx_case_entities_by_evidence', 'case_entities', ['evidence_id'], unique=False)
    op.create_index('idx_case_entities_lookup', 'case_entities', ['case_id', 'entity_type', 'entity_value'], unique=False)
    op.create_index(op.f('ix_case_entities_organization_id'), 'case_entities', ['organization_id'], unique=False)
    op.create_table('conversion_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('conversion_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_item_id', sa.String(length=36), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('runbook_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('source_type', sa.String(length=20), server_default='document', nullable=False),
    sa.Column('document_type', sa.String(length=50), server_default='runbook', nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.Text().with_variant(postgresql.ARRAY(String(length=50)), 'postgresql'), nullable=True),
    sa.Column('validation_passed', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('validation_warnings', sa.JSON(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('quality_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IS NULL OR severity IN ('low', 'medium', 'high', 'critical')", name='conversion_drafts_severity_check'),
    sa.CheckConstraint("status IN ('draft', 'verified', 'rejected', 'archived')", name='conversion_drafts_status_check'),
    sa.ForeignKeyConstraint(['conversion_id'], ['conversion_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.item_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_drafts_conversion_id'), 'conversion_drafts', ['conversion_id'], unique=False)
    op.create_index(op.f('ix_conversion_drafts_organization_id'), 'conversion_drafts', ['organization_id'], unique=False)
    op.create_index('ix_conversion_drafts_tags', 'conversion_drafts', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('hypothesis_evidence',
    sa.Column('hypothesis_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('linked_at_turn', sa.Integer(), nullable=True),
    sa.Column('linked_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("relationship_type IN ('supports', 'refutes', 'related')", name='hypothesis_evidence_relationship_check'),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name='hypothesis_evidence_confidence_range'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.evidence_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.hypothesis_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hypothesis_id', 'evidence_id')
    )
    op.create_index('ix_hypothesis_evidence_evidence', 'hypothesis_evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_evidence_organization_id'), 'hypothesis_evidence', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hypothesis_evidence_organization_id'), table_name='hypothesis_evidence')
    op.drop_index('ix_hypothesis_evidence_evidence', table_name='hypothesis_evidence')
    op.drop_table('hypothesis_evidence')
    # ix_conversion_drafts_tags may have already been consumed by migration 011
    # (SQLite table-recreate path) — guard against double-drop.
    op.execute(sa.text("DROP INDEX IF EXISTS ix_conversion_drafts_tags"))
    op.drop_index(op.f('ix_conversion_drafts_organization_id'), table_name='conversion_drafts')
    op.drop_index(op.f('ix_conversion_drafts_conversion_id'), table_name='conversion_drafts')
    op.drop_table('conversion_drafts')
    op.drop_index(op.f('ix_case_entities_organization_id'), table_name='case_entities')
    op.drop_index('idx_case_entities_lookup', table_name='case_entities')
    op.drop_index('idx_case_entities_by_evidence', table_name='case_entities')
    op.drop_table('case_entities')
    op.drop_index(op.f('ix_agent_tool_calls_tool_name'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_status'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_organization_id'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_execution_id'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_created_at'), table_name='agent_tool_calls')
    op.drop_table('agent_tool_calls')
    op.drop_index(op.f('ix_solutions_status'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_organization_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_hypothesis_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_created_by'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_case_id'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index('ix_evidence_tags', table_name='evidence', postgresql_using='gin')
    op.drop_index(op.f('ix_evidence_source_file_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_organization_id'), table_name='evidence')
    op.drop_index('ix_evidence_coverage', table_name='evidence')
    op.drop_index(op.f('ix_evidence_collected_at_turn'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_category'), table_name='evidence')
    op.drop_index('ix_evidence_case_is_primary', table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_conversion_jobs_user_id'), table_name='conversion_jobs')
    op.drop_index(op.f('ix_conversion_jobs_source_file_id'), table_name='conversion_jobs')
    op.drop_index(op.f('ix_conversion_jobs_organization_id'), table_name='conversion_jobs')
    op.drop_index(op.f('ix_conversion_jobs_case_id'), table_name='conversion_jobs')
    op.drop_table('conversion_jobs')
    op.drop_index(op.f('ix_agent_executions_status'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_session_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_organization_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_created_at'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_case_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_type'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_model'), table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index(op.f('ix_uploaded_files_uploaded_by'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_organization_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_content_hash'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_case_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_reports_organization_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_index('idx_reports_type_version', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_knowledge_suggestions_status'), table_name='knowledge_suggestions')
    op.drop_index(op.f('ix_knowledge_suggestions_pii_scan_status'), table_name='knowledge_suggestions')
    op.drop_index(op.f('ix_knowledge_suggestions_organization_id'), table_name='knowledge_suggestions')
    op.drop_index(op.f('ix_knowledge_suggestions_knowledge_item_id'), table_name='knowledge_suggestions')
    op.drop_index(op.f('ix_knowledge_suggestions_extracted_by'), table_name='knowledge_suggestions')
    op.drop_index(op.f('ix_knowledge_suggestions_created_at'), table_name='knowledge_suggestions')
    op.drop_index(op.f('ix_knowledge_suggestions_case_id'), table_name='knowledge_suggestions')
    op.drop_table('knowledge_suggestions')
    op.drop_index(op.f('ix_investigation_sessions_user_id'), table_name='investigation_sessions')
    op.drop_index(op.f('ix_investigation_sessions_status'), table_name='investigation_sessions')
    op.drop_index(op.f('ix_investigation_sessions_organization_id'), table_name='investigation_sessions')
    op.drop_index(op.f('ix_investigation_sessions_created_at'), table_name='investigation_sessions')
    op.drop_index(op.f('ix_investigation_sessions_case_id'), table_name='investigation_sessions')
    op.drop_table('investigation_sessions')
    op.drop_index(op.f('ix_hypotheses_status'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_organization_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_created_by'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_category'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_case_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_case_tags_tag'), table_name='case_tags')
    op.drop_index(op.f('ix_case_tags_organization_id'), table_name='case_tags')
    op.drop_index(op.f('ix_case_tags_case_id'), table_name='case_tags')
    op.drop_table('case_tags')
    op.drop_index(op.f('ix_case_messages_organization_id'), table_name='case_messages')
    op.drop_index(op.f('ix_case_messages_created_at'), table_name='case_messages')
    op.drop_index('ix_case_messages_case_turn', table_name='case_messages')
    op.drop_index(op.f('ix_case_messages_case_id'), table_name='case_messages')
    op.drop_index('ix_case_messages_case_created', table_name='case_messages')
    op.drop_table('case_messages')
    op.drop_index(op.f('ix_case_checkpoints_organization_id'), table_name='case_checkpoints')
    op.drop_index(op.f('ix_case_checkpoints_created_at'), table_name='case_checkpoints')
    op.drop_index('ix_case_checkpoints_case_turn', table_name='case_checkpoints')
    op.drop_index(op.f('ix_case_checkpoints_case_id'), table_name='case_checkpoints')
    op.drop_table('case_checkpoints')
    op.drop_index(op.f('ix_case_actions_organization_id'), table_name='case_actions')
    op.drop_index(op.f('ix_case_actions_case_id'), table_name='case_actions')
    op.drop_table('case_actions')
    op.drop_index('ix_team_members_team_id', table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_knowledge_items_verification_level'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_team_id'), table_name='knowledge_items')
    op.drop_index('ix_knowledge_items_tags', table_name='knowledge_items', postgresql_using='gin')
    op.drop_index(op.f('ix_knowledge_items_source_suggestion_id'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_scope'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_owner_id'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_organization_id'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_last_retrieved_at'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_item_type'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_is_published'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_created_at'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_category'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    op.drop_index(op.f('ix_cases_user_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_team_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_organization_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_last_activity_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_closed_at'), table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_user_audit_log_user_id', table_name='user_audit_log')
    op.drop_index('ix_user_audit_log_organization_id', table_name='user_audit_log')
    op.drop_index(op.f('ix_user_audit_log_event_type'), table_name='user_audit_log')
    op.drop_table('user_audit_log')
    op.drop_index('ix_teams_organization_id', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_org_members_role_id', table_name='organization_members')
    op.drop_index('ix_org_members_organization_id', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organizations_owner_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_enterprise_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('idx_auth_codes_expires_at', table_name='oauth_authorization_codes')
    op.drop_table('oauth_authorization_codes')
    op.drop_table('llm_config_overrides')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index(op.f('ix_users_enterprise_id'), table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index('idx_revoked_tokens_expires_at', table_name='oauth_revoked_tokens')
    op.drop_table('oauth_revoked_tokens')
    op.drop_index('ix_enterprises_slug', table_name='enterprises')
    op.drop_table('enterprises')
    # ### end Alembic commands ###
