"""001_clean_baseline

Clean baseline schema for FaultMaven. All 30 tables (auth, case, knowledge,
config) are autogenerated from SQLAlchemy ORM models, with RBAC seed data.

Revision ID: 424078e5aa04
Revises:
Create Date: 2026-03-17 19:19:25.116096
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '424078e5aa04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_items',
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('embedding_model', sa.String(length=128), nullable=False),
    sa.Column('embedding_vector', sa.Text(), nullable=True),
    sa.Column('embedding_version', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('verification_level', sa.Integer(), nullable=False),
    sa.Column('verification_reason', sa.String(length=512), nullable=True),
    sa.Column('verified_by', sa.String(length=64), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_suggestion_id', sa.String(length=64), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('not_helpful_count', sa.Integer(), nullable=False),
    sa.Column('last_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.CheckConstraint("item_type IN ('troubleshooting_guide', 'error_pattern', 'solution_template', 'api_documentation', 'configuration_guide', 'best_practice', 'faq', 'runbook')", name='knowledge_items_item_type_check'),
    sa.CheckConstraint('embedding_version >= 1', name='knowledge_items_embedding_version_check'),
    sa.CheckConstraint('helpful_count >= 0', name='knowledge_items_helpful_count_check'),
    sa.CheckConstraint('not_helpful_count >= 0', name='knowledge_items_not_helpful_count_check'),
    sa.CheckConstraint('verification_level >= 0 AND verification_level <= 2', name='knowledge_items_verification_level_check'),
    sa.CheckConstraint('view_count >= 0', name='knowledge_items_view_count_check'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_knowledge_items_category'), 'knowledge_items', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_items_created_at'), 'knowledge_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_items_is_published'), 'knowledge_items', ['is_published'], unique=False)
    op.create_index(op.f('ix_knowledge_items_item_type'), 'knowledge_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_knowledge_items_last_retrieved_at'), 'knowledge_items', ['last_retrieved_at'], unique=False)
    op.create_index(op.f('ix_knowledge_items_organization_id'), 'knowledge_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_items_source_suggestion_id'), 'knowledge_items', ['source_suggestion_id'], unique=False)
    op.create_index(op.f('ix_knowledge_items_verification_level'), 'knowledge_items', ['verification_level'], unique=False)
    op.create_table('knowledge_suggestions',
    sa.Column('suggestion_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('suggested_title', sa.String(length=512), nullable=False),
    sa.Column('suggested_content', sa.Text(), nullable=False),
    sa.Column('suggested_type', sa.String(length=64), nullable=False),
    sa.Column('extracted_by', sa.String(length=64), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('include_messages', sa.Boolean(), nullable=False),
    sa.Column('include_evidence', sa.Boolean(), nullable=False),
    sa.Column('pii_scan_status', sa.String(length=32), nullable=False),
    sa.Column('pii_scan_result', sa.Text(), nullable=True),
    sa.Column('pii_remediated_by', sa.String(length=64), nullable=True),
    sa.Column('pii_remediated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_case_title', sa.String(length=512), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('knowledge_item_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.CheckConstraint("pii_scan_status IN ('not_scanned', 'scanning', 'clean', 'pii_detected', 'remediated', 'scan_failed')", name='knowledge_suggestions_pii_scan_status_check'),
    sa.CheckConstraint("status IN ('pending_review', 'approved', 'rejected', 'draft')", name='knowledge_suggestions_status_check'),
    sa.CheckConstraint('evidence_count >= 0', name='knowledge_suggestions_evidence_count_check'),
    sa.CheckConstraint('message_count >= 0', name='knowledge_suggestions_message_count_check'),
    sa.PrimaryKeyConstraint('suggestion_id')
    )
    op.create_index(op.f('ix_knowledge_suggestions_case_id'), 'knowledge_suggestions', ['case_id'], unique=False)
    op.create_index(op.f('ix_knowledge_suggestions_created_at'), 'knowledge_suggestions', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_suggestions_extracted_by'), 'knowledge_suggestions', ['extracted_by'], unique=False)
    op.create_index(op.f('ix_knowledge_suggestions_knowledge_item_id'), 'knowledge_suggestions', ['knowledge_item_id'], unique=False)
    op.create_index(op.f('ix_knowledge_suggestions_organization_id'), 'knowledge_suggestions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_knowledge_suggestions_pii_scan_status'), 'knowledge_suggestions', ['pii_scan_status'], unique=False)
    op.create_index(op.f('ix_knowledge_suggestions_status'), 'knowledge_suggestions', ['status'], unique=False)
    op.create_table('llm_config_overrides',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('oauth_authorization_codes',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('code_challenge', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('idx_auth_codes_expires_at', 'oauth_authorization_codes', ['expires_at'], unique=False)
    op.create_table('oauth_revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index('idx_revoked_tokens_expires_at', 'oauth_revoked_tokens', ['expires_at'], unique=False)
    op.create_table('organizations',
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_tier', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('max_members', sa.Integer(), server_default='5', nullable=False),
    sa.Column('max_cases', sa.Integer(), nullable=True),
    sa.Column('settings', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('organization_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_organizations_owner_id', 'organizations', ['owner_id'], unique=False)
    op.create_index('ix_organizations_slug', 'organizations', ['slug'], unique=True)
    op.create_table('permissions',
    sa.Column('permission_id', sa.String(length=30), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('resource', 'action', name='permissions_resource_action_unique')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=20), server_default='organization', nullable=False),
    sa.Column('is_system_role', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.CheckConstraint('LENGTH(TRIM(user_id)) > 0', name='sessions_user_id_not_empty'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_organization_id'), 'sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('standalone_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=256), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=2048), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('linked_cases', sa.Text(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.CheckConstraint('LENGTH(TRIM(filename)) > 0', name='standalone_evidence_filename_not_empty'),
    sa.CheckConstraint('LENGTH(TRIM(storage_path)) > 0', name='standalone_evidence_storage_path_not_empty'),
    sa.CheckConstraint('size_bytes >= 0', name='standalone_evidence_size_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standalone_evidence_organization_id'), 'standalone_evidence', ['organization_id'], unique=False)
    op.create_index(op.f('ix_standalone_evidence_uploaded_at'), 'standalone_evidence', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_standalone_evidence_uploaded_by'), 'standalone_evidence', ['uploaded_by'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False),
    sa.Column('locale', sa.String(length=10), server_default='en-US', nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sso_provider', sa.String(length=50), nullable=True),
    sa.Column('sso_provider_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_password_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('roles', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_table('cases',
    sa.Column('case_id', sa.String(length=17), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('inquiry', sa.Text(), nullable=False),
    sa.Column('problem_verification', sa.Text(), nullable=True),
    sa.Column('working_conclusion', sa.Text(), nullable=True),
    sa.Column('root_cause_conclusion', sa.Text(), nullable=True),
    sa.Column('path_selection', sa.Text(), nullable=True),
    sa.Column('degraded_mode', sa.Text(), nullable=True),
    sa.Column('escalation_state', sa.Text(), nullable=True),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.Column('progress', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=20), nullable=True),
    sa.Column('team_id', sa.String(length=20), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('LENGTH(TRIM(title)) > 0', name='cases_title_not_empty'),
    sa.CheckConstraint('LENGTH(TRIM(user_id)) > 0', name='cases_user_id_not_empty'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_organization_id'), 'cases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cases_session_id'), 'cases', ['session_id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_team_id'), 'cases', ['team_id'], unique=False)
    op.create_index(op.f('ix_cases_user_id'), 'cases', ['user_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('role_id', sa.String(length=20), nullable=False),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invitation_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    op.create_index('ix_org_members_organization_id', 'organization_members', ['organization_id'], unique=False)
    op.create_index('ix_org_members_role_id', 'organization_members', ['role_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=20), nullable=False),
    sa.Column('permission_id', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('teams',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('organization_id', 'name', name='teams_organization_name_unique')
    )
    op.create_index('ix_teams_organization_id', 'teams', ['organization_id'], unique=False)
    op.create_table('user_audit_log',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_user_audit_log_event_type'), 'user_audit_log', ['event_type'], unique=False)
    op.create_index('ix_user_audit_log_organization_id', 'user_audit_log', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_user_audit_log_user_id', 'user_audit_log', ['user_id', 'created_at'], unique=False)
    op.create_table('agent_tool_calls',
    sa.Column('call_id', sa.String(length=20), nullable=False),
    sa.Column('case_id', sa.String(length=17), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_input', sa.Text(), nullable=False),
    sa.Column('tool_output', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'success', 'error')", name='agent_tool_calls_status_valid'),
    sa.CheckConstraint('LENGTH(TRIM(tool_name)) > 0', name='agent_tool_calls_tool_name_not_empty'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index(op.f('ix_agent_tool_calls_case_id'), 'agent_tool_calls', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_organization_id'), 'agent_tool_calls', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_status'), 'agent_tool_calls', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_tool_name'), 'agent_tool_calls', ['tool_name'], unique=False)
    op.create_table('case_actions',
    sa.Column('transition_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=17), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('transitioned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transition_id')
    )
    op.create_index(op.f('ix_case_actions_case_id'), 'case_actions', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_actions_organization_id'), 'case_actions', ['organization_id'], unique=False)
    op.create_table('case_checkpoints',
    sa.Column('checkpoint_id', sa.String(length=50), nullable=False),
    sa.Column('case_id', sa.String(length=17), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('case_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(snapshot_hash)) > 0', name='case_checkpoints_hash_not_empty'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_index(op.f('ix_case_checkpoints_case_id'), 'case_checkpoints', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_checkpoints_created_at'), 'case_checkpoints', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_checkpoints_organization_id'), 'case_checkpoints', ['organization_id'], unique=False)
    op.create_index('ix_case_turn', 'case_checkpoints', ['case_id', 'turn_number'], unique=False)
    op.create_table('case_messages',
    sa.Column('message_id', sa.String(length=20), nullable=False),
    sa.Column('case_id', sa.String(length=17), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.CheckConstraint('LENGTH(TRIM(content)) > 0', name='case_messages_content_not_empty'),
    sa.CheckConstraint('turn_number >= 0', name='case_messages_turn_nonnegative'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_case_messages_case_created', 'case_messages', ['case_id', 'created_at'], unique=False)
    op.create_index('idx_case_messages_case_turn', 'case_messages', ['case_id', 'turn_number'], unique=False)
    op.create_index(op.f('ix_case_messages_case_id'), 'case_messages', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_messages_created_at'), 'case_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_case_messages_organization_id'), 'case_messages', ['organization_id'], unique=False)
    op.create_table('case_tags',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=17), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(tag)) > 0', name='case_tags_tag_not_empty'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('case_id', 'tag', name='case_tags_unique')
    )
    op.create_index(op.f('ix_case_tags_case_id'), 'case_tags', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_tags_organization_id'), 'case_tags', ['organization_id'], unique=False)
    op.create_index(op.f('ix_case_tags_tag'), 'case_tags', ['tag'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(length=15), nullable=False),
    sa.Column('case_id', sa.String(length=17), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('source_type_new', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('preprocessed_content', sa.Text(), nullable=False),
    sa.Column('content_ref', sa.String(length=1000), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('collected_at_turn', sa.Integer(), nullable=True),
    sa.Column('source_file_id', sa.String(length=20), nullable=True),
    sa.Column('upload_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.CheckConstraint('LENGTH(TRIM(preprocessed_content)) > 0', name='evidence_content_not_empty'),
    sa.CheckConstraint('LENGTH(TRIM(summary)) > 0', name='evidence_summary_not_empty'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_category'), 'evidence', ['category'], unique=False)
    op.create_index(op.f('ix_evidence_collected_at_turn'), 'evidence', ['collected_at_turn'], unique=False)
    op.create_index(op.f('ix_evidence_content_hash'), 'evidence', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_organization_id'), 'evidence', ['organization_id'], unique=False)
    op.create_table('evidence_artifacts',
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=17), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=2048), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=256), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_backend', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.CheckConstraint('LENGTH(TRIM(file_path)) > 0', name='evidence_artifacts_file_path_not_empty'),
    sa.CheckConstraint('LENGTH(TRIM(original_filename)) > 0', name='evidence_artifacts_filename_not_empty'),
    sa.CheckConstraint('file_size >= 0', name='evidence_artifacts_file_size_non_negative'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_index(op.f('ix_evidence_artifacts_case_id'), 'evidence_artifacts', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_artifacts_created_at'), 'evidence_artifacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_artifacts_evidence_type'), 'evidence_artifacts', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_artifacts_organization_id'), 'evidence_artifacts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evidence_artifacts_user_id'), 'evidence_artifacts', ['user_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('hypothesis_id', sa.String(length=15), nullable=False),
    sa.Column('case_id', sa.String(length=17), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('likelihood', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('initial_likelihood', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('generated_at_turn', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_updated_turn', sa.Integer(), nullable=True),
    sa.Column('last_progress_at_turn', sa.Integer(), nullable=True),
    sa.Column('iterations_without_progress', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('generation_mode', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('retirement_reason', sa.Text(), nullable=True),
    sa.Column('evidence_links', sa.Text(), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('concluded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.CheckConstraint('LENGTH(TRIM(statement)) > 0', name='hypotheses_statement_not_empty'),
    sa.CheckConstraint('likelihood IS NULL OR (likelihood >= 0 AND likelihood <= 1)', name='hypotheses_likelihood_range'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hypothesis_id')
    )
    op.create_index(op.f('ix_hypotheses_case_id'), 'hypotheses', ['case_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_category'), 'hypotheses', ['category'], unique=False)
    op.create_index(op.f('ix_hypotheses_created_by'), 'hypotheses', ['created_by'], unique=False)
    op.create_index(op.f('ix_hypotheses_organization_id'), 'hypotheses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_status'), 'hypotheses', ['status'], unique=False)
    op.create_table('investigation_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=17), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_duration_ms', sa.Integer(), nullable=True),
    sa.Column('session_goal', sa.Text(), nullable=True),
    sa.Column('findings_summary', sa.Text(), nullable=True),
    sa.Column('total_token_usage', sa.Integer(), nullable=False),
    sa.Column('total_agent_executions', sa.Integer(), nullable=False),
    sa.Column('token_budget_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'paused', 'completed', 'abandoned')", name='investigation_sessions_status_check'),
    sa.CheckConstraint('token_budget_limit IS NULL OR token_budget_limit >= 0', name='investigation_sessions_budget_check'),
    sa.CheckConstraint('total_agent_executions >= 0', name='investigation_sessions_executions_check'),
    sa.CheckConstraint('total_duration_ms IS NULL OR total_duration_ms >= 0', name='investigation_sessions_duration_check'),
    sa.CheckConstraint('total_token_usage >= 0', name='investigation_sessions_token_usage_check'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_investigation_sessions_case_id'), 'investigation_sessions', ['case_id'], unique=False)
    op.create_index(op.f('ix_investigation_sessions_created_at'), 'investigation_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_investigation_sessions_organization_id'), 'investigation_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_investigation_sessions_status'), 'investigation_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_investigation_sessions_user_id'), 'investigation_sessions', ['user_id'], unique=False)
    op.create_table('solutions',
    sa.Column('solution_id', sa.String(length=15), nullable=False),
    sa.Column('case_id', sa.String(length=17), nullable=False),
    sa.Column('solution_type', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('immediate_action', sa.Text(), nullable=True),
    sa.Column('longterm_fix', sa.Text(), nullable=True),
    sa.Column('implementation_steps', sa.Text(), nullable=True),
    sa.Column('commands', sa.Text(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('estimated_effort', sa.String(length=50), nullable=True),
    sa.Column('verification_result', sa.Text(), nullable=True),
    sa.Column('verification_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('implemented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.CheckConstraint("risk_level IS NULL OR risk_level IN ('low', 'medium', 'high', 'critical')", name='solutions_risk_level_valid'),
    sa.CheckConstraint('LENGTH(TRIM(description)) > 0', name='solutions_description_not_empty'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('solution_id')
    )
    op.create_index(op.f('ix_solutions_case_id'), 'solutions', ['case_id'], unique=False)
    op.create_index(op.f('ix_solutions_created_by'), 'solutions', ['created_by'], unique=False)
    op.create_index(op.f('ix_solutions_organization_id'), 'solutions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_solutions_status'), 'solutions', ['status'], unique=False)
    op.create_table('team_members',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('team_role', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    op.create_index('ix_team_members_team_id', 'team_members', ['team_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('file_id', sa.String(length=15), nullable=False),
    sa.Column('case_id', sa.String(length=17), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at_turn', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('content_ref', sa.String(length=1000), nullable=True),
    sa.Column('preprocessing_summary', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.CheckConstraint('LENGTH(TRIM(filename)) > 0', name='uploaded_files_filename_not_empty'),
    sa.CheckConstraint('size_bytes > 0', name='uploaded_files_size_positive'),
    sa.CheckConstraint('uploaded_at_turn >= 0', name='uploaded_files_turn_nonnegative'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_uploaded_files_case_id'), 'uploaded_files', ['case_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_organization_id'), 'uploaded_files', ['organization_id'], unique=False)
    op.create_table('agent_executions',
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=17), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('agent_type', sa.String(length=64), nullable=False),
    sa.Column('agent_model', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_duration_ms', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('token_usage', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint("agent_type IN ('investigator', 'debugger', 'researcher', 'validator', 'reporter', 'custom')", name='agent_executions_agent_type_check'),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed', 'cancelled', 'timeout')", name='agent_executions_status_check'),
    sa.CheckConstraint('execution_duration_ms IS NULL OR execution_duration_ms >= 0', name='agent_executions_duration_check'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['investigation_sessions.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_agent_executions_agent_model'), 'agent_executions', ['agent_model'], unique=False)
    op.create_index(op.f('ix_agent_executions_agent_type'), 'agent_executions', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_executions_case_id'), 'agent_executions', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_created_at'), 'agent_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_executions_organization_id'), 'agent_executions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_session_id'), 'agent_executions', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_status'), 'agent_executions', ['status'], unique=False)
    op.create_table('agent_tool_calls_v2',
    sa.Column('tool_call_id', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('tool_input', sa.Text(), nullable=True),
    sa.Column('tool_output', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'success', 'failed')", name='agent_tool_calls_v2_status_check'),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name='agent_tool_calls_v2_duration_check'),
    sa.ForeignKeyConstraint(['execution_id'], ['agent_executions.execution_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_call_id')
    )
    op.create_index(op.f('ix_agent_tool_calls_v2_created_at'), 'agent_tool_calls_v2', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_v2_execution_id'), 'agent_tool_calls_v2', ['execution_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_v2_organization_id'), 'agent_tool_calls_v2', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_v2_status'), 'agent_tool_calls_v2', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tool_calls_v2_tool_name'), 'agent_tool_calls_v2', ['tool_name'], unique=False)

    # Seed RBAC data
    roles = sa.table('roles', sa.column('role_id'), sa.column('name'), sa.column('description'), sa.column('scope'), sa.column('is_system_role'))
    op.bulk_insert(roles, [
        {'role_id': 'role_super_admin', 'name': 'Super Admin', 'description': 'Full system access', 'scope': 'system', 'is_system_role': True},
        {'role_id': 'role_org_owner', 'name': 'Owner', 'description': 'Organization owner with full admin rights', 'scope': 'organization', 'is_system_role': True},
        {'role_id': 'role_org_admin', 'name': 'Admin', 'description': 'Organization administrator', 'scope': 'organization', 'is_system_role': True},
        {'role_id': 'role_org_member', 'name': 'Member', 'description': 'Standard organization member', 'scope': 'organization', 'is_system_role': True},
        {'role_id': 'role_org_viewer', 'name': 'Viewer', 'description': 'Read-only organization access', 'scope': 'organization', 'is_system_role': True},
        {'role_id': 'role_team_lead', 'name': 'Team Lead', 'description': 'Team leader with management rights', 'scope': 'team', 'is_system_role': True},
        {'role_id': 'role_team_member', 'name': 'Team Member', 'description': 'Standard team member', 'scope': 'team', 'is_system_role': True},
    ])

    permissions = sa.table('permissions', sa.column('permission_id'), sa.column('resource'), sa.column('action'), sa.column('description'))
    op.bulk_insert(permissions, [
        {'permission_id': 'perm_cases_read', 'resource': 'cases', 'action': 'read', 'description': 'View cases'},
        {'permission_id': 'perm_cases_write', 'resource': 'cases', 'action': 'write', 'description': 'Create and edit cases'},
        {'permission_id': 'perm_cases_delete', 'resource': 'cases', 'action': 'delete', 'description': 'Delete cases'},
        {'permission_id': 'perm_cases_manage', 'resource': 'cases', 'action': 'manage', 'description': 'Full case management'},
        {'permission_id': 'perm_kb_read', 'resource': 'knowledge_base', 'action': 'read', 'description': 'View knowledge base'},
        {'permission_id': 'perm_kb_write', 'resource': 'knowledge_base', 'action': 'write', 'description': 'Add to knowledge base'},
        {'permission_id': 'perm_kb_manage', 'resource': 'knowledge_base', 'action': 'manage', 'description': 'Manage knowledge base'},
        {'permission_id': 'perm_org_read', 'resource': 'organization', 'action': 'read', 'description': 'View organization settings'},
        {'permission_id': 'perm_org_write', 'resource': 'organization', 'action': 'write', 'description': 'Edit organization settings'},
        {'permission_id': 'perm_org_manage', 'resource': 'organization', 'action': 'manage', 'description': 'Full organization management'},
        {'permission_id': 'perm_users_read', 'resource': 'users', 'action': 'read', 'description': 'View users'},
        {'permission_id': 'perm_users_invite', 'resource': 'users', 'action': 'invite', 'description': 'Invite users'},
        {'permission_id': 'perm_users_manage', 'resource': 'users', 'action': 'manage', 'description': 'Manage users and roles'},
        {'permission_id': 'perm_teams_read', 'resource': 'teams', 'action': 'read', 'description': 'View teams'},
        {'permission_id': 'perm_teams_write', 'resource': 'teams', 'action': 'write', 'description': 'Create and edit teams'},
        {'permission_id': 'perm_teams_manage', 'resource': 'teams', 'action': 'manage', 'description': 'Full team management'},
    ])

    role_permissions = sa.table('role_permissions', sa.column('role_id'), sa.column('permission_id'))
    op.bulk_insert(role_permissions, [
        *[{'role_id': 'role_org_owner', 'permission_id': pid} for pid in [
            'perm_cases_read', 'perm_cases_write', 'perm_cases_delete', 'perm_cases_manage',
            'perm_kb_read', 'perm_kb_write', 'perm_kb_manage',
            'perm_org_read', 'perm_org_write', 'perm_org_manage',
            'perm_users_read', 'perm_users_invite', 'perm_users_manage',
            'perm_teams_read', 'perm_teams_write', 'perm_teams_manage']],
        *[{'role_id': 'role_org_member', 'permission_id': pid} for pid in [
            'perm_cases_read', 'perm_cases_write', 'perm_kb_read', 'perm_kb_write',
            'perm_teams_read', 'perm_users_read']],
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_tool_calls_v2_tool_name'), table_name='agent_tool_calls_v2')
    op.drop_index(op.f('ix_agent_tool_calls_v2_status'), table_name='agent_tool_calls_v2')
    op.drop_index(op.f('ix_agent_tool_calls_v2_organization_id'), table_name='agent_tool_calls_v2')
    op.drop_index(op.f('ix_agent_tool_calls_v2_execution_id'), table_name='agent_tool_calls_v2')
    op.drop_index(op.f('ix_agent_tool_calls_v2_created_at'), table_name='agent_tool_calls_v2')
    op.drop_table('agent_tool_calls_v2')
    op.drop_index(op.f('ix_agent_executions_status'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_session_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_organization_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_created_at'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_case_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_type'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_model'), table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index(op.f('ix_uploaded_files_organization_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_case_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index('ix_team_members_team_id', table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_solutions_status'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_organization_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_created_by'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_case_id'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index(op.f('ix_investigation_sessions_user_id'), table_name='investigation_sessions')
    op.drop_index(op.f('ix_investigation_sessions_status'), table_name='investigation_sessions')
    op.drop_index(op.f('ix_investigation_sessions_organization_id'), table_name='investigation_sessions')
    op.drop_index(op.f('ix_investigation_sessions_created_at'), table_name='investigation_sessions')
    op.drop_index(op.f('ix_investigation_sessions_case_id'), table_name='investigation_sessions')
    op.drop_table('investigation_sessions')
    op.drop_index(op.f('ix_hypotheses_status'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_organization_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_created_by'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_category'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_case_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_evidence_artifacts_user_id'), table_name='evidence_artifacts')
    op.drop_index(op.f('ix_evidence_artifacts_organization_id'), table_name='evidence_artifacts')
    op.drop_index(op.f('ix_evidence_artifacts_evidence_type'), table_name='evidence_artifacts')
    op.drop_index(op.f('ix_evidence_artifacts_created_at'), table_name='evidence_artifacts')
    op.drop_index(op.f('ix_evidence_artifacts_case_id'), table_name='evidence_artifacts')
    op.drop_table('evidence_artifacts')
    op.drop_index(op.f('ix_evidence_organization_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_content_hash'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_collected_at_turn'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_category'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_case_tags_tag'), table_name='case_tags')
    op.drop_index(op.f('ix_case_tags_organization_id'), table_name='case_tags')
    op.drop_index(op.f('ix_case_tags_case_id'), table_name='case_tags')
    op.drop_table('case_tags')
    op.drop_index(op.f('ix_case_messages_organization_id'), table_name='case_messages')
    op.drop_index(op.f('ix_case_messages_created_at'), table_name='case_messages')
    op.drop_index(op.f('ix_case_messages_case_id'), table_name='case_messages')
    op.drop_index('idx_case_messages_case_turn', table_name='case_messages')
    op.drop_index('idx_case_messages_case_created', table_name='case_messages')
    op.drop_table('case_messages')
    op.drop_index('ix_case_turn', table_name='case_checkpoints')
    op.drop_index(op.f('ix_case_checkpoints_organization_id'), table_name='case_checkpoints')
    op.drop_index(op.f('ix_case_checkpoints_created_at'), table_name='case_checkpoints')
    op.drop_index(op.f('ix_case_checkpoints_case_id'), table_name='case_checkpoints')
    op.drop_table('case_checkpoints')
    op.drop_index(op.f('ix_case_actions_organization_id'), table_name='case_actions')
    op.drop_index(op.f('ix_case_actions_case_id'), table_name='case_actions')
    op.drop_table('case_actions')
    op.drop_index(op.f('ix_agent_tool_calls_tool_name'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_status'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_organization_id'), table_name='agent_tool_calls')
    op.drop_index(op.f('ix_agent_tool_calls_case_id'), table_name='agent_tool_calls')
    op.drop_table('agent_tool_calls')
    op.drop_index('ix_user_audit_log_user_id', table_name='user_audit_log')
    op.drop_index('ix_user_audit_log_organization_id', table_name='user_audit_log')
    op.drop_index(op.f('ix_user_audit_log_event_type'), table_name='user_audit_log')
    op.drop_table('user_audit_log')
    op.drop_index('ix_teams_organization_id', table_name='teams')
    op.drop_table('teams')
    op.drop_table('role_permissions')
    op.drop_index('ix_org_members_role_id', table_name='organization_members')
    op.drop_index('ix_org_members_organization_id', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_cases_user_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_team_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_session_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_organization_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_standalone_evidence_uploaded_by'), table_name='standalone_evidence')
    op.drop_index(op.f('ix_standalone_evidence_uploaded_at'), table_name='standalone_evidence')
    op.drop_index(op.f('ix_standalone_evidence_organization_id'), table_name='standalone_evidence')
    op.drop_table('standalone_evidence')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_organization_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index('ix_organizations_slug', table_name='organizations')
    op.drop_index('ix_organizations_owner_id', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('idx_revoked_tokens_expires_at', table_name='oauth_revoked_tokens')
    op.drop_table('oauth_revoked_tokens')
    op.drop_index('idx_auth_codes_expires_at', table_name='oauth_authorization_codes')
    op.drop_table('oauth_authorization_codes')
    op.drop_table('llm_config_overrides')
    op.drop_index(op.f('ix_knowledge_suggestions_status'), table_name='knowledge_suggestions')
    op.drop_index(op.f('ix_knowledge_suggestions_pii_scan_status'), table_name='knowledge_suggestions')
    op.drop_index(op.f('ix_knowledge_suggestions_organization_id'), table_name='knowledge_suggestions')
    op.drop_index(op.f('ix_knowledge_suggestions_knowledge_item_id'), table_name='knowledge_suggestions')
    op.drop_index(op.f('ix_knowledge_suggestions_extracted_by'), table_name='knowledge_suggestions')
    op.drop_index(op.f('ix_knowledge_suggestions_created_at'), table_name='knowledge_suggestions')
    op.drop_index(op.f('ix_knowledge_suggestions_case_id'), table_name='knowledge_suggestions')
    op.drop_table('knowledge_suggestions')
    op.drop_index(op.f('ix_knowledge_items_verification_level'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_source_suggestion_id'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_organization_id'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_last_retrieved_at'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_item_type'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_is_published'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_created_at'), table_name='knowledge_items')
    op.drop_index(op.f('ix_knowledge_items_category'), table_name='knowledge_items')
    op.drop_table('knowledge_items')
    # ### end Alembic commands ###
