"""Add scope isolation to knowledge items

Revision ID: 0a6eafc2e4cf
Revises: 424078e5aa04
Create Date: 2026-03-24 00:41:31.363304

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a6eafc2e4cf"
down_revision: str | Sequence[str] | None = "424078e5aa04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_items", sa.Column("scope", sa.String(length=20), nullable=False)
    )
    op.add_column(
        "knowledge_items", sa.Column("owner_id", sa.String(length=36), nullable=True)
    )
    op.add_column(
        "knowledge_items", sa.Column("team_id", sa.String(length=36), nullable=True)
    )
    op.create_index(
        op.f("ix_knowledge_items_owner_id"),
        "knowledge_items",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_items_scope"), "knowledge_items", ["scope"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_items_team_id"), "knowledge_items", ["team_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_items_team_id"), table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_scope"), table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_owner_id"), table_name="knowledge_items")
    op.drop_column("knowledge_items", "team_id")
    op.drop_column("knowledge_items", "owner_id")
    op.drop_column("knowledge_items", "scope")
    # ### end Alembic commands ###
