"""Deterministic knowledge-item id derivation for pre-deployed runbooks.

Shared single source of truth so the startup KB bootstrap
(``faultmaven.bootstrap.kb_init``) and the on-disk scan
(``faultmaven.modules.knowledge.domain.services.conversion_service``) agree on
the id a given runbook file maps to. The scan uses it to recognize files the
bootstrap already published directly into ``knowledge_items`` (which never get
a ``conversion_drafts`` row), so it doesn't manufacture phantom drafts for
already-ingested runbooks.
"""

from __future__ import annotations

import hashlib


def item_id_from_runbook_id(runbook_id: str) -> str:
    """Stable item_id derived from a runbook's frontmatter ``id``.

    Format: ``kb_{sha256(runbook_id)[:12]}``. Deterministic across runs;
    avoids collision with the random-uuid item_ids generated by the
    user-facing ``verify_draft`` path.
    """
    digest = hashlib.sha256(runbook_id.encode("utf-8")).hexdigest()[:12]
    return f"kb_{digest}"
