"""Runbook identifier, on-disk-name minting, and the runbook write path.

Three related jobs, kept together because they all answer "what is this runbook
called, and where does it live": deterministic knowledge-item **id** derivation
for pre-deployed runbooks, the safe on-disk **filename**/path components a
runbook is written under (``runbook_filename`` / ``safe_path_component`` /
``runbook_id_from_parts``, #1213), and the single containment-checked
**write/resolve** helper every runbook file operation goes through
(``knowledge_root`` / ``resolve_runbook_path`` / ``write_runbook_file``).

The containment helper is deliberately in the same module as the name minting.
#1215's review showed the two cannot be reasoned about apart: a filename guard
is worthless if the directory has already escaped, and a containment assertion
anchored on that directory is circular. One module owns both halves so a change
to either is made where the other is visible.

Id derivation:

Shared single source of truth so the startup KB bootstrap
(``faultmaven.bootstrap.kb_init``) and the on-disk scan
(``faultmaven.modules.knowledge.domain.services.conversion_service``) agree on
the id a given runbook file maps to. The scan uses it to recognize files the
bootstrap already published directly into ``knowledge_items`` (which never get
a ``conversion_drafts`` row), so it doesn't manufacture phantom drafts for
already-ingested runbooks.
"""

from __future__ import annotations

import hashlib
import re
from pathlib import Path
from uuid import uuid4

from faultmaven.utils.path_containment import PathEscape, resolve_within_root

# A bootstrap-published (platform built-in) runbook has a deterministic
# ``kb_<12-hex>`` item_id (see ``item_id_from_runbook_id``). This is the
# provenance discriminator the inventory surface uses to decide delete
# semantics: built-ins are *unpublished* (the file on disk would resurrect a
# hard delete on the next bootstrap), authored items are *hard-deleted*.
#
# The anchor is EXACTLY 12 hex chars on purpose: the manual-create path
# (``authored_item_id`` below) emits ``kb_<16-hex>``, so a
# loose prefix match would misclassify manually-authored items as built-ins.
_BUILTIN_ITEM_ID_RE = re.compile(r"^kb_[0-9a-f]{12}$")


def item_id_from_runbook_id(runbook_id: str) -> str:
    """Stable item_id derived from a runbook's frontmatter ``id``.

    Format: ``kb_{sha256(runbook_id)[:12]}``. Deterministic across runs;
    avoids collision with the random-uuid item_ids generated by the
    user-facing ``verify_draft`` path.
    """
    digest = hashlib.sha256(runbook_id.encode("utf-8")).hexdigest()[:12]
    return f"kb_{digest}"


def is_builtin_item_id(item_id: str) -> bool:
    """True if ``item_id`` is a bootstrap-published platform built-in.

    Built-ins match ``^kb_[0-9a-f]{12}$`` exactly. Authored items
    (verify_draft / API create) use random UUIDs or ``kb_<16-hex>`` and do
    not match. Used by the inventory delete path to pick unpublish (built-in)
    vs hard-delete (authored).
    """
    return bool(item_id and _BUILTIN_ITEM_ID_RE.match(item_id))


def authored_item_id() -> str:
    """item_id for a USER-authored runbook (verify_draft / API create).

    ``kb_<16-hex>`` — 16 hex chars so it NEVER matches the 12-hex built-in
    discriminator (``_BUILTIN_ITEM_ID_RE`` / ``is_builtin_item_id``). Authored
    items must be hard-deletable on request and MUST NOT be swept by the
    bootstrap orphan-prune, which deletes only ids matching the built-in
    pattern. A 12-hex authored id would be silently prune-deleted on the next
    redeploy with a changed pack — this helper is the single mint point that
    keeps authored ids out of that pattern.
    """
    return f"kb_{uuid4().hex[:16]}"


# Everything outside the allowlist collapses to a single hyphen. This is an
# ALLOWLIST on purpose (#1213): a denylist here would have to anticipate
# ``../``, ``..\``, ``....//``, absolute paths, NUL and control bytes, and
# whatever the filesystem normalises next. An allowlist has to anticipate
# nothing — a character either survives or it does not.
_SLUG_RE = re.compile(r"[^a-z0-9]+")

#: Per-part bound. Both parts plus a hyphen and ``.md`` stay well inside the
#: 255-byte NAME_MAX of every filesystem we target, AND inside
#: ``uploaded_files.filename`` (``String(255)``), which a too-long name would
#: otherwise fail on at INSERT rather than at the write.
_MAX_SLUG_CHARS = 60
_MAX_SUFFIX_CHARS = 40

#: Bound for a **persisted runbook id** (``runbook_id_from_parts``). Numerically
#: equal to ``_MAX_SLUG_CHARS`` today and deliberately a SEPARATE constant: that
#: one bounds a filename component (NAME_MAX / ``uploaded_files.filename``),
#: this one bounds a value already written into ``conversion_drafts.runbook_id``
#: and into runbook frontmatter. Tightening the filename bound must not silently
#: re-mint ids that already exist in the database.
_MAX_RUNBOOK_ID_CHARS = 60
#: An over-long id keeps up to 55 characters of readable slug plus ``-`` plus a
#: 4-hex disambiguator, landing on ``_MAX_RUNBOOK_ID_CHARS`` (or one shorter,
#: when the truncation point lands on a hyphen — see ``runbook_id_from_parts``).
_RUNBOOK_ID_HASH_CHARS = 4

#: Stem for the id of a ``(service, title)`` pair with no allowlisted
#: characters at all. Followed by ``-`` and ``_EMPTY_SLUG_HASH_CHARS`` hex of
#: the RAW pair, so two such pairs get DIFFERENT ids while the same pair keeps
#: getting the same one.
_EMPTY_SLUG_STEM = "runbook"
_EMPTY_SLUG_HASH_CHARS = 8

#: Recognises an id minted by that branch. Used by callers that want a more
#: informative fallback than a bare hash (``SuggestionService._mint_id`` prefers
#: the case's own stem when the draft's title carried nothing readable).
_HASH_ONLY_ID_RE = re.compile(
    rf"^{_EMPTY_SLUG_STEM}-[0-9a-f]{{{_EMPTY_SLUG_HASH_CHARS}}}$"
)


def _slug(value: str | None) -> str:
    """Lowercase, allowlist-filtered, hyphen-collapsed. May return ``""``."""
    return _SLUG_RE.sub("-", (value or "").lower()).strip("-")


def safe_path_component(value: str | None, *, fallback: str = "unknown") -> str:
    """One directory-name component, guaranteed to be a single safe segment.

    For the identifiers interpolated into scope directories
    (``team_{team_id}`` / ``user_{owner_id}``). Those are auth-context values
    rather than request bodies, so they are a lower-risk source than a title —
    but they are still interpolated into a path, and #1213's review showed the
    containment check is worthless if the DIRECTORY has already escaped: an
    ``owner_id`` of ``../../../../escaped`` sent the write to ``<cwd>/escaped``
    while every filename-level guard passed.
    """
    return _slug(value)[:_MAX_SLUG_CHARS] or fallback


def runbook_filename(title: str | None, document_id: str | None) -> str:
    """Safe on-disk filename for a runbook, derived from its ``title``.

    ``title`` is caller-supplied — a form field on ``POST /knowledge/documents``
    and, on the suggestion-approval path, an LLM-generated ``suggested_title`` —
    so it is untrusted input that used to reach ``Path`` unfiltered. A title of
    ``../../../etc/pwned`` produced
    ``data/knowledge/global/../../../etc/pwned-75e6.md``, which resolves outside
    the knowledge tree, and the content was written there (#1213).

    **Invariant: the result always matches ``[a-z0-9][a-z0-9-]*\.md``** — one
    path component, no separator, no traversal sequence, no NUL, no leading dot,
    no device name. Both parts are filtered and bounded independently, and the
    uuid fallback is applied AFTER filtering: applying it before meant a
    ``document_id`` that filtered to nothing produced the bare name ``".md"`` —
    a hidden dotfile that also collided with every other such document.

    ``document_id`` is appended rather than a fresh random suffix so the file is
    traceable to the row that owns it, and so two runbooks sharing a title do
    not collide. It is filtered and bounded too: it is an id today, but nothing
    in the signature enforces that, and the review that produced this docstring
    found a 412-character name from a long one.

    A title with no allowlisted characters — punctuation-only, or a non-latin
    script — yields the suffix alone. Less readable, and the right trade:
    admitting non-latin characters means reasoning about unicode separator
    look-alikes (FULLWIDTH SOLIDUS and friends) and normalization form, which is
    the analysis this design avoids. This is a storage name; the human-readable
    title is on the row.
    """
    slug = _slug(title)[:_MAX_SLUG_CHARS].strip("-")
    suffix = _slug(document_id)[:_MAX_SUFFIX_CHARS].strip("-")
    if not suffix:
        # AFTER filtering, never before — see the docstring.
        suffix = uuid4().hex[:16]
    stem = f"{slug}-{suffix}" if slug else suffix
    return f"{stem}.md"


def runbook_id_from_parts(service: str | None, title: str | None) -> str:
    """The PERSISTED runbook id for a ``(service, title)`` pair.

    Single mint point for the two call sites that write this value to the
    database and into runbook frontmatter — ``generate_runbook_id`` (the LLM
    conversion path) and ``ConversionService.create_runbook_from_template``
    (the manual path). Both previously carried their own byte-identical copy of
    this expression; the copies are what #1213's review recorded as "the slug
    rule now exists in three places".

    **It shares ``_slug`` with the filename helpers and nothing else, on
    purpose.** The character rule is one rule and a tightening there should
    reach every consumer. The two *policies* over it must not be merged:

    - **Over-length.** An id keeps 55 slug characters plus an md5 disambiguator
      so two long titles that share a 60-character prefix still get distinct
      ids. ``safe_path_component`` just truncates — a filename collision is
      resolved by the id suffix ``runbook_filename`` appends.
    - **Empty result.** An id with no allowlisted characters gets a
      hash-derived stem here (see below). ``safe_path_component`` substitutes
      the fixed literal ``"unknown"``, because a path component only has to be
      *a* safe segment — a filename collision there is resolved by the id
      suffix ``runbook_filename`` appends, and there is no such backstop for an
      id.

    **Invariant: the result always matches ``^[a-z0-9]+(-[a-z0-9]+)*$``** — the
    grammar ``RunbookValidator`` enforces on frontmatter ``id``, non-empty by
    construction. Two branches used to break it (#1230, #1243):

    - A ``(service, title)`` pair with no allowlisted characters — punctuation
      only, or a non-latin script — returned ``""``. Two such runbooks
      persisted two ``conversion_drafts`` rows with ``runbook_id = ''`` and one
      identical ``item_id_from_runbook_id('')``, which no unique constraint
      rejected. They now get ``runbook-<8 hex of the RAW pair>``: non-empty,
      kebab, deterministic (the disk scan reconciles a file to a row by this
      id, so the same pair must keep minting the same value), and — **among
      pairs that reach this branch** — different for different pairs. That
      scoping is deliberate and load-bearing; see the boundary paragraph below,
      because the branch fires only when the WHOLE pair filters to nothing.
    - Truncation could land on a hyphen, so ``slug[:55] + "-" + md5`` emitted a
      **double** hyphen — 5 of the 91 shipped runbook titles, measured with
      their real frontmatter ``service``. The kept prefix is now ``rstrip``ed
      of hyphens before the disambiguator is joined on. The hash is still taken
      over the FULL slug, so two long titles sharing a 55-character prefix stay
      distinct.

    A third change is not about validity at all, and is called out separately
    because it DOES alter an id that was valid:

    - **A ``None`` part is normalised to ``""``** (see the comment on ``raw``).
      Stringified, it became the literal ``"none"``, which is not empty — so
      the hash branch could not see it and three punctuation-only titles under
      a ``None`` service all minted ``"none"``. ``"none-title"`` becomes
      ``"title"``.

    **Nothing REACHABLE that was already valid changed.** The first two
    branches fire only on input whose old id the validator already rejected
    (empty is a missing required field *and* a grammar failure; a double hyphen
    is a grammar failure), so no *usable* persisted id is re-minted. The third
    fires only on ``None``, which no call site can pass — all four supply a
    ``str``. That is the property that made this change affordable, and
    ``tests/unit/utils/test_runbook_id_consolidation.py`` pins it as a
    differential against the pre-consolidation originals rather than as a
    comment, with the ``None`` exemption named and bounded to exactly the
    inputs that carry one.

    What this does NOT do is make the id globally unique. Two distinct titles
    that slug identically still mint the same id, and they must — determinism
    is what the scan's file-to-row reconciliation depends on, and a pure
    function cannot see the other rows. Two shapes reach that, and the second
    is worth naming because it looks like it should have been covered:

    - ``("svc", "Foo Bar")`` and ``("svc", "foo-bar")`` — the same slug.
    - ``("redis", "!!!")`` and ``("redis", "???")`` — **both mint ``"redis"``**.
      The hash branch does not fire, because it keys on the pair filtering to
      *nothing*, and here the service survives. Extending it to "the title
      contributed nothing" would re-mint ``("redis", "")``-shaped ids that are
      valid today, which is the one thing this change is not allowed to do.

    (Two long titles cut to the same 55 characters are NOT in that list — the
    md5 disambiguator separates those.)

    Both are enforced where the other rows are visible: the partial unique
    index on ``(organization_id, runbook_id)`` from migration 045, surfaced as
    a 409 by ``ConversionService._raise_if_runbook_id_taken``.

    The md5 is a disambiguator, not a secret: its input is the slug (or, on the
    empty branch, the raw pair), which is the id's own visible prefix.
    """
    # ``or ""`` rather than letting the f-string stringify: ``None`` used to
    # become the literal ``"none"``, so ``(None, "!!!")``, ``(None, "???")`` and
    # ``(None, "。。。")`` all minted ``"none"`` — the #1230 collision, reintroduced
    # through the one input the signature admits and the hash branch cannot
    # see (the slug is not empty, it is ``"none"``). It also put a ``none-``
    # prefix on every ordinary title. No call site passes ``None`` today — all
    # four supply a ``str`` — so no persisted id can have been minted this way;
    # the signature is the promise being repaired.
    raw = f"{service or ''}-{title or ''}"
    slug = _slug(raw)
    if not slug:
        digest = hashlib.md5(raw.encode("utf-8"), usedforsecurity=False).hexdigest()[
            :_EMPTY_SLUG_HASH_CHARS
        ]
        return f"{_EMPTY_SLUG_STEM}-{digest}"
    if len(slug) > _MAX_RUNBOOK_ID_CHARS:
        suffix = hashlib.md5(slug.encode(), usedforsecurity=False).hexdigest()[
            :_RUNBOOK_ID_HASH_CHARS
        ]
        keep = _MAX_RUNBOOK_ID_CHARS - _RUNBOOK_ID_HASH_CHARS - 1
        # ``rstrip`` BEFORE joining: ``_slug`` never emits a run of hyphens, so
        # the only way a double hyphen reaches the output is the cut landing on
        # one. The prefix cannot strip to empty — ``_slug`` also never emits a
        # LEADING hyphen.
        slug = slug[:keep].rstrip("-") + "-" + suffix
    return slug


def is_hash_only_runbook_id(runbook_id: str | None) -> bool:
    """True if ``runbook_id`` carries no readable text — only the hash stem.

    ``runbook_id_from_parts`` emits ``runbook-<8 hex>`` when the
    ``(service, title)`` pair filters to nothing (#1230). The id is valid and
    unique, but it says nothing about what the runbook is, so a caller holding
    a better name can prefer that instead. ``SuggestionService._mint_id`` does:
    it falls back to the case's own stem, which is opaque but at least
    traceable to the incident.

    It is a *signal*, not a guard — an id that is not hash-only is not thereby
    guaranteed readable, and a real title of ``"Runbook 3fa2b1c0"`` on an empty
    service would match. Nothing security-relevant hangs on either direction.
    """
    return bool(runbook_id and _HASH_ONLY_ID_RE.match(runbook_id))


def draft_filename(runbook_id: str | None) -> str:
    """On-disk filename for a draft whose id is ``runbook_id``.

    Normally just ``f"{runbook_id}.md"`` — the draft file is named after its
    id, and the scan reconciles the two by that name.

    The exception is an id that filtered to ``""``:
    ``runbook_id_from_parts`` returns empty for a punctuation-only or non-latin
    ``(service, title)`` pair, and ``scope_dir / ".md"`` passes containment
    (it is inside the tree) while being a **hidden file that every such runbook
    in that scope shares**. Measured on the branch that lacked this: two
    template runbooks in one scope produced one ``.md`` on disk, the second
    silently overwriting the first, and deleting either unlinked the other's
    file.

    A uuid stem is substituted instead — the same shape and the same reason as
    ``runbook_filename``'s suffix fallback. This is a FILENAME decision only: it
    does not touch ``runbook_id_from_parts``, so nothing already persisted in
    ``conversion_drafts.runbook_id`` is re-minted. The empty *id* itself remains
    a defect on the persisted-identifier side, out of scope here and reported
    separately.
    """
    stem = _slug(runbook_id)[:_MAX_SLUG_CHARS].strip("-")
    if not stem:
        stem = uuid4().hex[:16]
    return f"{stem}.md"


# =============================================================================
# Where a runbook lives on disk, and the only sanctioned way to touch it
# =============================================================================


def knowledge_root() -> Path:
    """The one anchor every runbook containment check resolves against.

    ``KnowledgeService.upload_document`` and ``ConversionService._data_dir``
    each used to spell this literal themselves. Two spellings of an anchor is
    one spelling too many: the guard is only as good as the agreement that both
    sides mean the same tree.

    Relative on purpose. Every persisted ``conversion_drafts.file_path`` is
    relative (``data/knowledge/...``), and the scan pass matches those strings
    against ``str(md_file)`` from a walk of this same relative root — an
    absolute root here would make every tracked path a miss and the scan would
    manufacture duplicate drafts. Anchor and candidate resolve against the same
    cwd, so containment is unaffected by where the process runs.
    """
    return Path("data/knowledge")


class RunbookPathEscape(PathEscape):
    """A runbook path that is not, or cannot be shown to be, inside the tree.

    Covers both halves of "this path is not safe to touch": it resolved outside
    the knowledge root, or it could not be resolved at all (a symlink loop, a
    permission error, a name too long). Callers act on both the same way —
    refuse the filesystem operation — so distinguishing them at the type level
    would buy nothing and invite one of the two to be forgotten.

    Subclasses ``PathEscape`` (itself a ``ValueError``) so it stays compatible
    with the guard #1215 shipped inline at the upload write site, and is its own
    type so a caller that must degrade rather than fail (a listing skipping one
    bad row, the scan skipping one bad file) can catch precisely this and
    nothing else — and NOT a refusal from the evidence-storage tree, which
    shares the containment rule (#1235) but not the degrade-and-continue
    contract.

    The message carries the resolved absolute paths, which are useful in a
    server log and must never reach a client. Service callers translate it to a
    typed domain exception whose client-facing message names only the row.
    """


def resolve_runbook_path(path: str | Path, *, source: str, root: Path) -> Path:
    """Resolve ``path``, refusing anything not strictly inside the tree.

    Call this before ANY filesystem operation on a runbook path — read, write,
    or unlink — and act on the returned resolved path.

    ``root`` is REQUIRED, deliberately. It defaulted to ``knowledge_root()``
    once, and that default was a bypass no test could see: every test redirects
    the root through ``ConversionService._data_dir``, so a future caller that
    simply omitted ``root=`` would silently check against the real
    ``data/knowledge`` and pass every suite while guarding the wrong tree.
    Making it required turns that mistake into a ``TypeError`` at import time.

    Anchored on the ROOT of the tree, never on the directory the path is in:
    anchoring on the containing directory is circular, since an escaped
    directory trivially contains its own child. That circularity is the exact
    defect #1215's first round shipped, and it passed its own test.

    ``source`` names where the path came from, and is carried into the error.
    For a value read back from the database that means naming the row — a path
    persisted before the mint points were sanitised is precisely the case this
    exists for, and "some draft is bad" is not an actionable message.

    The result is STRICTLY inside the root — the root itself is refused. It is
    a directory, so a write to it would fail anyway, but ``write_runbook_file``
    would first ``mkdir`` its *parent*, which is outside the tree.

    **Symlinks are resolved, so a link pointing out of the tree is refused.**
    That is the security property — containment is about where a path *lands*,
    not what it is named — and it has a deployment consequence worth stating
    plainly: a knowledge tree assembled out of symlinks (``data/knowledge/team_x
    -> /mnt/share``) worked before this guard and does not work now. Callers on
    the destructive paths (the scan) therefore SKIP what they refuse rather than
    deleting it, so an operator on such a layout loses access, not data.

    ``Path.resolve()`` can also fail outright — ``RuntimeError`` on a symlink
    loop (measured on CPython 3.11), ``OSError`` for permissions, a too-long
    name, or a filesystem that is gone, and ``ValueError`` on an embedded NUL
    (``a\x00b`` — a genuinely reachable pre-#1215 DB value, measured). An
    unresolvable path is not a containable path, so all three become
    ``RunbookPathEscape`` rather than escaping as themselves: letting a bare
    ``RuntimeError`` through killed ``delete_draft`` before its soft-delete and
    aborted whole scans, and a bare ``ValueError`` — the type
    ``RunbookPathEscape`` itself subclasses — would sail straight past a caller
    catching only ``RunbookPathEscape``, which is every degrading caller here.

    The two resolves are separated so the error can name **which** path failed.
    ``root`` (``self._data_dir``) failing is an operator's misconfiguration and
    names the tree; ``path`` failing is the untrusted DB value and names the
    row. Conflating them sent an operator chasing the innocent draft file when
    the root was at fault.

    The rule itself lives in ``utils.path_containment.resolve_within_root``,
    shared with the evidence-storage backend since #1235. Only the wording and
    the exception type are this subsystem's (see ``RunbookPathEscape``); the
    messages are unchanged from the inline implementation this replaced.

    Raises:
        RunbookPathEscape: the path is outside the root, or cannot be resolved.
    """
    return resolve_within_root(
        path,
        root=root,
        source=source,
        subject="runbook path",
        tree="knowledge",
        error=RunbookPathEscape,
    )


def write_runbook_file(
    path: str | Path,
    content: str,
    *,
    source: str,
    root: Path,
    encoding: str = "utf-8",
) -> Path:
    """Write ``content`` to ``path``, but only if ``path`` is inside the tree.

    Validation happens BEFORE the ``mkdir``. ``mkdir(parents=True)`` on an
    escaped path materialises attacker-chosen directories outside the tree
    whatever the write then does — the second half of #1215's round-1 defect,
    which left ``escaped/`` on disk even where the file write was refused.

    ``root`` is required for the reason given on ``resolve_runbook_path``.

    Returns the resolved path. Callers persisting a path to the database should
    keep persisting the ORIGINAL (relative) string, not this one; see
    ``knowledge_root``.
    """
    resolved = resolve_runbook_path(path, source=source, root=root)
    resolved.parent.mkdir(parents=True, exist_ok=True)
    resolved.write_text(content, encoding=encoding)
    return resolved
