"""Tests for the in-repo v4 cause extractor (``runbook_cause_extractor``).

The extractor is the produce-side counterpart of the KB pack builder's
``_extract_causes``: it turns a case→runbook conversion's v4 markdown into the
``metadata["causes"]`` record the Phase-4 seeder consumes, so a resolved case
re-enters diagnosis as structured candidates.

The load-bearing test is the **golden cross-check**: the extractor's output must
byte-match the record the upstream kb-toolkit builder computes for the same
markdown (produce/consume symmetry). The two repos cannot import one another, so
the expected record is vendored (``fixtures/runbook_cause_extractor/``) — it was
generated by running ``kb_toolkit.core.pack_builder._extract_causes`` on the
vendored fixture; regenerate both together if the shared grammar changes.
"""

import json
from pathlib import Path

import pytest

from faultmaven.modules.knowledge.domain.services.runbook_cause_extractor import (
    extract_causes,
)

pytestmark = pytest.mark.unit

_FIXTURES = Path(__file__).parent / "fixtures" / "runbook_cause_extractor"


def _load_golden() -> tuple[str, list]:
    content = (_FIXTURES / "golden_runbook.md").read_text(encoding="utf-8")
    expected = json.loads(
        (_FIXTURES / "golden_expected.json").read_text(encoding="utf-8")
    )
    return content, expected


# ---------------------------------------------------------------------------
# Golden cross-check — produce/consume symmetry with kb-toolkit
# ---------------------------------------------------------------------------


def test_golden_cross_check_matches_kb_toolkit_builder():
    """Extractor output is byte-identical to the kb-toolkit pack builder's for a
    fixture exercising every grammar branch: a multi-rung chain, a ``converges``
    edge, a multi-indicator rung, quadrant-tagged interventions, and the fallback
    Cause (``[Default]``, empty chain)."""
    content, expected = _load_golden()
    assert extract_causes(content) == expected


def test_golden_covers_every_record_field():
    """Guard the fixture itself stays representative: the expected record must
    exercise chain_nodes/edges, a converges edge, multi-value rung_indicators,
    interventions, and a fallback cause — else the golden silently narrows."""
    _, expected = _load_golden()
    assert any(c["chain_nodes"] and c["chain_edges"] for c in expected)
    assert any(e.get("converges") for c in expected for e in c["chain_edges"])
    assert any(
        len(vals) > 1 for c in expected for vals in c["rung_indicators"].values()
    )
    assert any(c["interventions"] for c in expected)
    assert any(c["is_fallback_cause"] for c in expected)


# ---------------------------------------------------------------------------
# Field-level structure
# ---------------------------------------------------------------------------

_CHAIN_RUNBOOK = """## Causes

### Cause A: Disk full
**Statement:** The data volume reached 100% utilization.
**Chain:**
- root: A runaway process writes unbounded logs
- s1: Free space drops below the write threshold
- D: Writes fail and the service errors
**Indicators:**
- root: [Step 1] log volume grows without rotation
**Interventions:**
- **remediation** (root): Add log rotation. **Verification:** volume stabilizes.
"""


def test_single_linear_chain_nodes_edges_and_types():
    (cause,) = extract_causes(_CHAIN_RUNBOOK)
    assert cause["cause_letter"] == "A"
    assert cause["cause_name"] == "Disk full"
    assert cause["is_fallback_cause"] is False
    assert [n["node_type"] for n in cause["chain_nodes"]] == [
        "root",
        "intermediate",
        "problem",
    ]
    assert cause["chain_edges"] == [
        {"cause_ref": "root", "effect_ref": "s1"},
        {"cause_ref": "s1", "effect_ref": "D"},
    ]


def test_html_comments_stripped_from_chain_and_indicators():
    content = """## Causes

### Cause A: X
**Statement:** S
**Chain:**
- root: real statement <!-- match: some-directive -->
- D: the problem
**Indicators:**
- root: [Symptom] observable <!-- annotation -->
**Interventions:**
- **remediation** (root): fix
"""
    (cause,) = extract_causes(content)
    root = cause["chain_nodes"][0]
    assert root["statement"] == "real statement"
    assert cause["rung_indicators"]["root"] == ["[Symptom] observable"]


def test_converges_directive_is_an_edge_not_a_node():
    content = """## Causes

### Cause A: X
**Statement:** S
**Chain:**
- root: the root
- converges: B.s1
**Indicators:**
- root: [Symptom] x
**Interventions:**
- **remediation** (root): fix
"""
    (cause,) = extract_causes(content)
    # converges does not add a node ...
    assert [n["ref"] for n in cause["chain_nodes"]] == ["root"]
    # ... it records a convergence edge from the prior rung onto B.s1.
    assert cause["chain_edges"] == [
        {"cause_ref": "root", "effect_ref": "B.s1", "converges": True}
    ]


# ---------------------------------------------------------------------------
# Best-effort / adversarial — malformed pieces skipped, never raised
# ---------------------------------------------------------------------------


def test_no_causes_section_returns_empty():
    assert extract_causes("# Title\n\n## Overview\nno causes here\n") == []


def test_empty_string_returns_empty():
    assert extract_causes("") == []


def test_cause_heading_outside_causes_section_is_ignored():
    # A ``### Cause``-style heading in another section must not be parsed.
    content = """## Diagnostic Steps
### Cause A: not a real cause heading

## Causes

### Cause A: real cause
**Statement:** S
**Interventions:**
- **remediation** (root): fix
"""
    causes = extract_causes(content)
    assert len(causes) == 1
    assert causes[0]["cause_statement"] == "S"


def test_chainless_cause_yields_empty_chain_not_error():
    # RULE-4 makes **Chain** optional for a simple one-step cause. The extractor
    # emits an empty chain (the seeder synthesizes root→D from the Statement).
    content = """## Causes

### Cause A: Simple one-step cause
**Statement:** The config flag was set to the wrong value.
**Indicators:**
- root: [Symptom] feature behaves incorrectly
**Interventions:**
- **remediation** (root): correct the flag. **Verification:** behavior restored.
"""
    (cause,) = extract_causes(content)
    assert cause["chain_nodes"] == []
    assert cause["chain_edges"] == []
    assert cause["cause_statement"] == "The config flag was set to the wrong value."
    assert cause["is_fallback_cause"] is False


def test_malformed_intervention_and_missing_fields_do_not_raise():
    # Garbage interventions / missing sub-fields are skipped, not raised.
    content = """## Causes

### Cause A: Sparse cause
**Statement:** only a statement, nothing else structured
**Interventions:**
- not a tagged intervention bullet
- **remediation** malformed no parens
"""
    (cause,) = extract_causes(content)
    assert cause["cause_statement"] == "only a statement, nothing else structured"
    assert cause["chain_nodes"] == []
    assert cause["interventions"] == []  # neither bullet is a valid quadrant mark
