name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: docker.io
  # IMAGE_NAME will be set based on repository name
  # For fm-case-service repo, IMAGE_NAME = faultmaven/fm-case-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/faultmaven/${{ github.event.repository.name }}
          tags: |
            # Tag with version on tags (v1.0.0 -> 1.0.0)
            type=semver,pattern={{version}}
            # Tag with major.minor on tags (v1.0.0 -> 1.0)
            type=semver,pattern={{major}}.{{minor}}
            # Tag with major on tags (v1.0.0 -> 1)
            type=semver,pattern={{major}}
            # Tag with 'latest' on main branch
            type=raw,value=latest,enable={{is_default_branch}}
            # Tag with commit SHA (for traceability)
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: Image digest
        if: github.event_name != 'pull_request'
        run: echo "Image pushed with digest ${{ steps.build-and-push.outputs.digest }}"

      - name: Update Docker Hub description
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: faultmaven/${{ github.event.repository.name }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md
        continue-on-error: true
