"""Locust load testing script for FaultMaven API.

This script defines user behaviors for load testing the FaultMaven API.
It simulates realistic user patterns including case creation, retrieval,
listing, and updates.

Usage:
    # Install locust (included in requirements-test.txt)
    pip install locust

    # Run with UI (opens browser at http://localhost:8089)
    locust -f tests/load/locustfile.py --host=http://localhost:8000

    # Headless mode for CI/CD
    locust -f tests/load/locustfile.py \
           --host=http://localhost:8000 \
           --users 50 \
           --spawn-rate 10 \
           --run-time 60s \
           --headless

    # Using the runner script
    ./scripts/run_load_tests.sh local
"""

import random
import string
import uuid

from locust import HttpUser, between, task


def random_string(length: int = 10) -> str:
    """Generate random string for test data."""
    return "".join(random.choices(string.ascii_letters + string.digits, k=length))


def random_case_id() -> str:
    """Generate a valid case ID matching pattern ^case_[a-f0-9]{12}$."""
    return f"case_{uuid.uuid4().hex[:12]}"


class FaultMavenUser(HttpUser):
    """Simulated FaultMaven user behavior.

    Represents a typical user interacting with the case management API.
    Task weights reflect realistic usage patterns:
    - 50% reads (get case)
    - 30% case creation
    - 20% list operations
    """

    wait_time = between(1, 3)  # Wait 1-3 seconds between tasks

    def on_start(self):
        """Called when user starts - initialize test state."""
        self.case_ids = []
        self.user_id = f"load-test-user-{random_string(8)}"
        self.org_id = f"load-test-org-{random_string(6)}"

    @task(3)
    def create_case(self):
        """Create a new case (30% of traffic).

        POST /api/v1/cases
        """
        case_id = random_case_id()
        response = self.client.post(
            "/api/v1/cases",
            json={
                "case_id": case_id,
                "user_id": self.user_id,
                "organization_id": self.org_id,
                "title": f"Load Test Case {random_string(5)}",
                "description": f"Generated by load test: {random_string(100)}",
                "status": "consulting",
            },
            name="/api/v1/cases [POST]",
        )

        if response.status_code in (200, 201):
            data = response.json()
            created_id = data.get("case_id", case_id)
            self.case_ids.append(created_id)
            # Keep only last 100 case IDs to avoid memory growth
            if len(self.case_ids) > 100:
                self.case_ids = self.case_ids[-100:]

    @task(5)
    def get_case(self):
        """Retrieve a case (50% of traffic).

        GET /api/v1/cases/:id
        """
        if not self.case_ids:
            return

        case_id = random.choice(self.case_ids)
        self.client.get(
            f"/api/v1/cases/{case_id}",
            name="/api/v1/cases/:id [GET]",
        )

    @task(2)
    def list_cases(self):
        """List cases (20% of traffic).

        GET /api/v1/cases
        """
        self.client.get(
            f"/api/v1/cases?user_id={self.user_id}&limit=50&offset=0",
            name="/api/v1/cases [GET]",
        )

    @task(1)
    def update_case(self):
        """Update a case (10% of traffic).

        PUT /api/v1/cases/:id
        """
        if not self.case_ids:
            return

        case_id = random.choice(self.case_ids)
        self.client.put(
            f"/api/v1/cases/{case_id}",
            json={
                "title": f"Updated - {random_string(10)}",
                "description": f"Updated description - {random_string(50)}",
            },
            name="/api/v1/cases/:id [PUT]",
        )

    @task(1)
    def search_cases(self):
        """Search cases (10% of traffic).

        GET /api/v1/cases/search
        """
        search_terms = ["error", "timeout", "connection", "database", "memory"]
        term = random.choice(search_terms)
        self.client.get(
            f"/api/v1/cases/search?query={term}&user_id={self.user_id}&limit=20",
            name="/api/v1/cases/search [GET]",
        )


class SessionUser(HttpUser):
    """Simulated session management user.

    Tests session creation and retrieval operations.
    """

    wait_time = between(0.5, 2)

    def on_start(self):
        """Initialize session test state."""
        self.session_ids = []
        self.user_id = f"session-test-user-{random_string(8)}"

    @task(3)
    def create_session(self):
        """Create a new session.

        POST /api/v1/sessions
        """
        session_id = str(uuid.uuid4())
        response = self.client.post(
            "/api/v1/sessions",
            json={
                "session_id": session_id,
                "user_id": self.user_id,
            },
            name="/api/v1/sessions [POST]",
        )

        if response.status_code in (200, 201):
            self.session_ids.append(session_id)
            if len(self.session_ids) > 50:
                self.session_ids = self.session_ids[-50:]

    @task(5)
    def get_session(self):
        """Retrieve a session.

        GET /api/v1/sessions/:id
        """
        if not self.session_ids:
            return

        session_id = random.choice(self.session_ids)
        self.client.get(
            f"/api/v1/sessions/{session_id}",
            name="/api/v1/sessions/:id [GET]",
        )

    @task(1)
    def touch_session(self):
        """Update session last_accessed.

        PUT /api/v1/sessions/:id/touch
        """
        if not self.session_ids:
            return

        session_id = random.choice(self.session_ids)
        self.client.put(
            f"/api/v1/sessions/{session_id}/touch",
            name="/api/v1/sessions/:id/touch [PUT]",
        )


class StressTestUser(HttpUser):
    """Aggressive user for stress testing.

    Used to test system behavior under extreme load.
    Minimal wait time between requests.
    """

    wait_time = between(0.1, 0.5)  # Minimal wait time

    def on_start(self):
        """Initialize stress test state."""
        self.user_id = f"stress-user-{random_string(8)}"
        self.org_id = f"stress-org-{random_string(6)}"

    @task
    def create_cases_rapidly(self):
        """Create cases as fast as possible for stress testing."""
        case_id = random_case_id()
        self.client.post(
            "/api/v1/cases",
            json={
                "case_id": case_id,
                "user_id": self.user_id,
                "organization_id": self.org_id,
                "title": f"Stress Test {random_string(5)}",
                "description": "Rapid creation test",
                "status": "consulting",
            },
            name="[STRESS] POST /api/v1/cases",
        )


class HealthCheckUser(HttpUser):
    """User that only checks health endpoints.

    Useful for baseline availability testing.
    """

    wait_time = between(5, 10)

    @task
    def health_check(self):
        """Check health endpoint."""
        self.client.get(
            "/health",
            name="/health [GET]",
        )

    @task
    def readiness_check(self):
        """Check readiness endpoint."""
        self.client.get(
            "/ready",
            name="/ready [GET]",
        )
