#!/bin/bash
#
# Install FaultMaven's version-controlled git hooks.
#
# Points git at the tracked .githooks/ directory (core.hooksPath) so the hooks
# stay in sync with the repo — no per-clone copy into .git/hooks/ that can
# drift. Run once per clone:
#
#     ./scripts/install-git-hooks.sh
#
# Installs:
#   pre-commit     auto-format staged Python with black
#   post-merge     warn when a stamped virtualenv falls behind its lockfile
#   post-checkout  the same, after a branch change
#
# The two staleness hooks warn only — they never touch an environment — and stay
# silent unless ./scripts/sync-venv.sh has stamped a venv. They add nothing for
# anyone not using it.
#
# None of these scan for secrets. The pre-commit FRAMEWORK
# (.pre-commit-config.yaml) additionally runs secret/API-key/RSA detection; if
# it is already installed, this script refuses to override it unless you pass
# --force, because core.hooksPath would bypass those security hooks.
#
# To use the full framework instead:
#     git config --unset core.hooksPath && pip install pre-commit && pre-commit install

set -euo pipefail

FORCE=false
[ "${1:-}" = "--force" ] && FORCE=true

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

if [ ! -d .githooks ]; then
    echo "✗ .githooks/ not found at repo root ($ROOT)" >&2
    exit 1
fi

# Guard: setting core.hooksPath makes git ignore .git/hooks/ entirely. If the
# pre-commit framework is installed there, overriding it would silently disable
# its secret-scanning hooks. Refuse unless --force.
FRAMEWORK_HOOK="$(git rev-parse --git-path hooks/pre-commit)"
if [ "$FORCE" != true ] && [ -f "$FRAMEWORK_HOOK" ] && grep -q 'generated by pre-commit' "$FRAMEWORK_HOOK" 2>/dev/null; then
    echo "⚠ The pre-commit FRAMEWORK is installed ($FRAMEWORK_HOOK)." >&2
    echo "  It runs secret/API-key/RSA detection (.pre-commit-config.yaml)." >&2
    echo "  Pointing core.hooksPath at .githooks would BYPASS those hooks," >&2
    echo "  leaving only the black formatter — a security downgrade." >&2
    echo "" >&2
    echo "  • Keep the framework (recommended): do nothing." >&2
    echo "  • Override anyway (black-only): ./scripts/install-git-hooks.sh --force" >&2
    exit 1
fi

chmod +x .githooks/* 2>/dev/null || true
git config core.hooksPath .githooks
echo "✓ git hooks installed (core.hooksPath → .githooks)"
echo "    pre-commit     black-formats staged Python"
echo "    post-merge     warns when a stamped venv falls behind its lockfile"
echo "    post-checkout  the same, after a branch change"
echo "  Note: these do NOT scan for secrets/keys."
echo "  For secret scanning too, use the pre-commit framework (see header)."

# Verify black matches the version CI enforces (formatting is version-sensitive).
PINNED="$("$ROOT/scripts/black-pinned-version.sh" 2>/dev/null || true)"
if [ -x .venv/bin/black ] && .venv/bin/black --version >/dev/null 2>&1; then
    HAVE="$(.venv/bin/black --version | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1)"
    if [ "$HAVE" = "$PINNED" ]; then
        echo "✓ .venv black $HAVE matches pinned $PINNED (CI runs 'black --check')"
    else
        echo "⚠ .venv black $HAVE != pinned $PINNED — run: .venv/bin/pip install black==$PINNED"
    fi
else
    echo "⚠ black not found in .venv — run: pip install -e \".[dev]\"  (installs black==$PINNED)"
fi
